In [3]:
import pandas as pd

In [ ]:
## What is Pandas

Pandas is open-source library that is used for data manupulation and data analysis.

It provide fast, flexiable and expressive data stracture.

It return the data in series or dataframe that is similar to lables , relation , and tabuler data.

In [4]:
## create dataframe from the given dictionary

data = {
    "Name":["Amit","Rahul","Jay","Salman","Katrina","Virat"],
    "Salary":[23000, 56000, 34000,57000,56000,66000],
    "Age":[34,56,45,33,23,32]}

In [5]:
data

{'Name': ['Amit', 'Rahul', 'Jay', 'Salman', 'Katrina', 'Virat'],
 'Salary': [23000, 56000, 34000, 57000, 56000, 66000],
 'Age': [34, 56, 45, 33, 23, 32]}

In [6]:
df = pd.DataFrame(data)

In [7]:
df

      Name  Salary  Age
0     Amit   23000   34
1    Rahul   56000   56
2      Jay   34000   45
3   Salman   57000   33
4  Katrina   56000   23
5    Virat   66000   32

In [8]:
type(df)

pandas.core.frame.DataFrame

In [21]:
## list to dataframe
Fruits = ["Apple","Gauva","Plam","Pomigranad","Blackberry"]
Price=[500,600,400,130]

In [22]:
fruits_data = list(zip(Fruits,Price))

In [23]:
fruits_data

[('Apple', 500), ('Gauva', 600), ('Plam', 400), ('Pomigranad', 130)]

In [24]:
df1= pd.DataFrame(fruits_data, columns= ['Fruits','Price'])

In [25]:
df1

       Fruits  Price
0       Apple    500
1       Gauva    600
2        Plam    400
3  Pomigranad    130

In [26]:
## empty dataframe
df3 = pd.DataFrame()

In [17]:
type(df3)

pandas.core.frame.DataFrame

In [27]:
df3

Empty DataFrame
Columns: []
Index: []

In [28]:
df3['Fruits'] = Fruits
df3['Price']=Price

ValueError: Length of values (4) does not match length of index (5)

In [20]:
df3

       Fruits  Price
0       Apple    500
1       Gauva    600
2        Plam    400
3  Pomigranad    130
4  Blackberry    300

In [51]:
## function that will take n number of list to create dataframe out of that
import logging

logging.basicConfig(level=logging.INFO)

def list_to_dataframe(*lists): ## 3 list of 5 length  ### case 2 --> 3 list 5,4,5
    try:
        length_iterator = list(map(lambda x : len(x),lists)) # [5,5,5] , ##[5,4,5] -->[5,4]
        
        logging.info(f"length of each list  is length_iterator = {length_iterator}")
        
        x = set(length_iterator) # [4,4,4] --> {4}
        logging.info(f"length of x after removing the duplicate x= {x}")
        
        if len(x)!=1:
            raise ValueError("length of the given list is not same")
        else:
            data=list(zip(*lists))
            logging.info(f"here is your data after zipping{data}")
            result = pd.DataFrame(data)
        return result
    except Exception as e:
        logging.error({"type":"error", "info":str(e)})

In [53]:
## pass three list parameter and convert that into data frame

name= ["Rahul","Sanjeev","Sharma","Avinav"]
age = [20,24,56,45]
salary = [56000, 45000, 340000, 67000]

df4=list_to_dataframe(name,age,salary)

INFO:root:length of each list  is length_iterator = [4, 4, 4]
INFO:root:length of x after removing the duplicate x= {4}
INFO:root:here is your data after zipping[('Rahul', 20, 56000), ('Sanjeev', 24, 45000), ('Sharma', 56, 340000), ('Avinav', 45, 67000)]

In [54]:
df4.columns= ['name','age','Salary']

In [49]:
df4

      name  age  Salary
0    Rahul   20   56000
1  Sanjeev   24   45000
2   Sharma   56  340000
3   Avinav   34   67000

In [58]:
## read the data from excel

patient_file_path= r"C:\Users\prash\Desktop\Python_for_all_YT_Playlist\data\patients_data.xlsx"

patient_data = pd.read_excel(patient_file_path)

In [59]:
patient_data

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [60]:
excel_file= pd.ExcelFile(patient_file_path)

In [63]:
excel_file.sheet_names

['Patients_2025', 'Patients_2026']

In [64]:
Patients_2025_date = pd.read_excel(excel_file,sheet_name= 'Patients_2025')

In [65]:
Patients_2026_date = pd.read_excel(excel_file,sheet_name= 'Patients_2026')

In [66]:
Patients_2025_date

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [67]:
Patients_2026_date

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,Year
0,1001,Aarav Mehta,78,aarav.mehta384@yahoo.com,POL625423,Premium,2026
1,1002,Aarav Verma,32,aarav.verma271@yahoo.com,POL930599,Basic,2026
2,1003,Vihaan Verma,40,vihaan.verma345@outlook.com,POL456865,Platinum,2026
3,1004,Aditya Mehta,18,aditya.mehta579@outlook.com,POL982259,Platinum,2026
4,1005,Aarav Singh,39,aarav.singh126@outlook.com,POL742545,Basic,2026
...,...,...,...,...,...,...,...
995,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026
996,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026
997,1998,Aarav Sharma,72,aarav.sharma12@yahoo.com,POL362369,Platinum,2026
998,1999,Ishaan Joshi,65,ishaan.joshi92@outlook.com,POL921223,Premium,2026
999,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026

In [68]:
## read the data from the csv 

csv_file_path = r"C:\Users\prash\Desktop\Python_for_all_YT_Playlist\data\patients_data.csv"

csv_data = pd.read_csv(csv_file_path)

In [69]:
csv_data

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type
0,1,Aditya Reddy,60,aditya.reddy437@outlook.com,POL701385,Gold
1,2,Aditya Verma,69,aditya.verma669@outlook.com,POL908515,Gold
2,3,Vivaan Reddy,58,vivaan.reddy696@yahoo.com,POL098395,Basic
3,4,Sai Gupta,76,sai.gupta699@gmail.com,POL802266,Basic
4,5,Ishaan Mehta,77,ishaan.mehta156@outlook.com,POL423233,Gold
...,...,...,...,...,...,...
995,996,Aditya Verma,41,aditya.verma839@yahoo.com,POL265181,Platinum
996,997,Aarav Gupta,63,aarav.gupta900@gmail.com,POL797105,Platinum
997,998,Vivaan Gupta,40,vivaan.gupta159@gmail.com,POL713191,Gold
998,999,Ishaan Verma,45,ishaan.verma817@gmail.com,POL146295,Basic
999,1000,Vihaan Patel,35,vihaan.patel222@yahoo.com,POL144496,Premium

In [70]:
## read the data from json

json_file_path=r"C:\Users\prash\Desktop\Python_for_all_YT_Playlist\data\patients_data.json"

pd.read_json(json_file_path)

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type
0,1,Aditya Reddy,60,aditya.reddy437@outlook.com,POL701385,Gold
1,2,Aditya Verma,69,aditya.verma669@outlook.com,POL908515,Gold
2,3,Vivaan Reddy,58,vivaan.reddy696@yahoo.com,POL098395,Basic
3,4,Sai Gupta,76,sai.gupta699@gmail.com,POL802266,Basic
4,5,Ishaan Mehta,77,ishaan.mehta156@outlook.com,POL423233,Gold
...,...,...,...,...,...,...
995,996,Aditya Verma,41,aditya.verma839@yahoo.com,POL265181,Platinum
996,997,Aarav Gupta,63,aarav.gupta900@gmail.com,POL797105,Platinum
997,998,Vivaan Gupta,40,vivaan.gupta159@gmail.com,POL713191,Gold
998,999,Ishaan Verma,45,ishaan.verma817@gmail.com,POL146295,Basic
999,1000,Vihaan Patel,35,vihaan.patel222@yahoo.com,POL144496,Premium

In [ ]:
1. dict
2. list
3. Custom function to read data from n list
4. Excel file , sheet specific
5. CSV
6. Json

In [72]:
df =Patients_2025_date

In [75]:
df

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [74]:
## how mnay rows and columns do we have

df.shape

(1000, 7)

In [76]:
df.size

7000

In [78]:
## data types and over all view of the data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Patient_ID     1000 non-null   int64
 1   Patient_Name   1000 non-null   object
 2   Age            1000 non-null   int64
 3   Email          1000 non-null   object
 4   Policy_Number  1000 non-null   object
 5   Policy_Type    1000 non-null   object
 6   year           1000 non-null   int64
dtypes: int64(3), object(4)
memory usage: 54.8+ KB

In [79]:
## i want to see top 5 records
df.head()

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025

In [80]:
## only bottom 5 records

df.tail()

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [81]:
## I want to see 20 records from the top

df.head(20)

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
5,6,Aditya Gupta,33,aditya.gupta574@yahoo.com,POL350037,Basic,2025
6,7,Vihaan Patel,56,vihaan.patel300@outlook.com,POL986252,Basic,2025
7,8,Aditya Yadav,53,aditya.yadav682@outlook.com,POL341551,Platinum,2025
8,9,Sai Yadav,45,sai.yadav975@gmail.com,POL440267,Gold,2025
9,10,Aditya Sharma,23,aditya.sharma396@gmail.com,POL938553,Gold,2025
10,11,Reyansh Yadav,69,reyansh.yadav432@gmail.com,POL676644,Gold,2025
11,12,Pranav Singh,30,pranav.singh95@yahoo.com,POL698348,Gold,2025
12,13,Ishaan Singh,23,ishaan.singh184@gmail.com,POL286469,Platinum,2025
13,14,Sai Kumar,35,sai.kumar179@gmail.com,POL701515,Platinum,2025
14,15,Ishaan Gupta,58,ishaan.gupta374@yahoo.com,POL069482,Platinum,2025
15,16,Aditya Mehta,38,aditya.mehta885@gmail.com,POL028707,Gold,2025
16,17,Reyansh Joshi,22,reyansh.joshi145@outlook.com,POL344833,Gold,2025
17,18,Vivaan Verma,44,vivaan.verma358@gmail.com,POL079916,Premium,2025
18,19,Pranav Singh,53,pranav.singh399@gmail.com,POL412488,Basic,2025
19,20,Sai Patel,52,sai.patel760@gmail.com,POL188458,Premium,2025

In [86]:
df.tail(25)

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
975,976,Reyansh Patel,28,reyansh.patel62@outlook.com,POL511704,Premium,2025
976,977,Krishna Sharma,36,krishna.sharma255@gmail.com,POL906950,Basic,2025
977,978,Vivaan Yadav,44,vivaan.yadav183@gmail.com,POL725642,Basic,2025
978,979,Reyansh Yadav,48,reyansh.yadav654@gmail.com,POL736990,Basic,2025
979,980,Vihaan Gupta,29,vihaan.gupta880@outlook.com,POL038984,Premium,2025
980,981,Aarav Reddy,39,aarav.reddy441@gmail.com,POL400447,Premium,2025
981,982,Vivaan Reddy,18,vivaan.reddy710@yahoo.com,POL831541,Gold,2025
982,983,Reyansh Patel,20,reyansh.patel789@gmail.com,POL976549,Basic,2025
983,984,Aditya Reddy,56,aditya.reddy409@gmail.com,POL219318,Gold,2025
984,985,Sai Mehta,74,sai.mehta51@outlook.com,POL829079,Basic,2025
985,986,Vivaan Reddy,35,vivaan.reddy717@outlook.com,POL024632,Basic,2025
986,987,Krishna Singh,42,krishna.singh24@outlook.com,POL268940,Basic,2025
987,988,Reyansh Verma,30,reyansh.verma743@outlook.com,POL966448,Basic,2025
988,989,Sai Reddy,28,sai.reddy786@yahoo.com,POL109584,Premium,2025
989,990,Ishaan Singh,36,ishaan.singh103@yahoo.com,POL585250,Premium,2025
990,991,Aarav Kumar,34,aarav.kumar294@outlook.com,POL694930,Gold,2025
991,992,Sai Reddy,62,sai.reddy600@outlook.com,POL079714,Basic,2025
992,993,Vivaan Mehta,23,vivaan.mehta928@yahoo.com,POL486384,Premium,2025
993,994,Pranav Mehta,77,pranav.mehta919@yahoo.com,POL065312,Premium,2025
994,995,Aarav Yadav,66,aarav.yadav625@yahoo.com,POL304066,Basic,2025
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [87]:
## I want only columns name

df.columns

Index(['Patient_ID', 'Patient_Name', 'Age', 'Email', 'Policy_Number',
       'Policy_Type', 'year'],
      dtype='object')

In [88]:
df.describe()

        Patient_ID          Age    year
count  1000.000000  1000.000000  1000.0
mean    500.500000    48.075000  2025.0
std     288.819436    18.360296     0.0
min       1.000000    18.000000  2025.0
25%     250.750000    32.000000  2025.0
50%     500.500000    48.000000  2025.0
75%     750.250000    63.000000  2025.0
max    1000.000000    80.000000  2025.0

In [92]:
type(df.Age)

pandas.core.series.Series

In [ ]:
## Series: 


We have discussed about the dataframe but we have not discussed about the series

### What is series

Aseries in pandas is one dimensional labeled array.

It has two main part value and index(lables)

In [94]:
Fruits

['Apple', 'Gauva', 'Plam', 'Pomigranad', 'Blackberry']

In [100]:
Price.append(30)

In [101]:
Price

[500, 600, 400, 130, 30]

In [107]:
age.append(20)

In [108]:
age

[20, 24, 56, 45, 20]

In [111]:
name

['Rahul', 'Sanjeev', 'Sharma', 'Avinav']

In [112]:
salary

[56000, 45000, 340000, 67000]

In [116]:
age=age[0:4]

In [117]:
age

[20, 24, 56, 45]

In [119]:
df

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [105]:
s

Apple         500
Gauva         600
Plam          400
Pomigranad    130
Blackberry     30
dtype: int64

In [121]:
## i want to get only one column

df.Age

0      22
1      40
2      51
3      36
4      23
       ..
995    32
996    67
997    27
998    49
999    72
Name: Age, Length: 1000, dtype: int64

In [124]:
type(df[['Age']])

pandas.core.frame.DataFrame

In [125]:
df['Age']

0      22
1      40
2      51
3      36
4      23
       ..
995    32
996    67
997    27
998    49
999    72
Name: Age, Length: 1000, dtype: int64

In [126]:
df.columns

Index(['Patient_ID', 'Patient_Name', 'Age', 'Email', 'Policy_Number',
       'Policy_Type', 'year'],
      dtype='object')

In [129]:
df[['Patient_Name','Age','Policy_Number']]

      Patient_Name  Age Policy_Number
0    Krishna Reddy   22     POL602544
1      Arjun Gupta   40     POL856642
2     Vivaan Singh   51     POL512045
3      Arjun Kumar   36     POL132724
4    Krishna Verma   23     POL060110
..             ...  ...           ...
995   Vivaan Verma   32     POL973107
996    Arjun Mehta   67     POL755200
997  Krishna Gupta   27     POL970351
998   Pranav Verma   49     POL343885
999  Reyansh Patel   72     POL418617

[1000 rows x 3 columns]

In [130]:
df

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [ ]:
## get all the columns along with 20 to 30 rowns numbers

df.iloc[20:31,:] ## iloc -- index location 

## syntax of iloc is 

dataframe.iloc[range_rows, range_columns]

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
20,21,Vihaan Kumar,73,vihaan.kumar651@outlook.com,POL996694,Basic,2025
21,22,Sai Verma,60,sai.verma422@outlook.com,POL752117,Premium,2025
22,23,Vihaan Verma,43,vihaan.verma972@outlook.com,POL926834,Platinum,2025
23,24,Aditya Gupta,37,aditya.gupta843@yahoo.com,POL722573,Gold,2025
24,25,Pranav Kumar,25,pranav.kumar649@yahoo.com,POL542704,Platinum,2025
25,26,Aditya Sharma,61,aditya.sharma1@outlook.com,POL352573,Premium,2025
26,27,Arjun Kumar,43,arjun.kumar396@outlook.com,POL806142,Premium,2025
27,28,Arjun Joshi,70,arjun.joshi601@gmail.com,POL331281,Platinum,2025
28,29,Aditya Joshi,41,aditya.joshi111@yahoo.com,POL065819,Gold,2025
29,30,Vivaan Patel,44,vivaan.patel698@outlook.com,POL492011,Gold,2025
30,31,Reyansh Sharma,48,reyansh.sharma154@outlook.com,POL492841,Gold,2025

In [136]:
## get records from 15 to 25 index for column --> Patient_name , Policy_Type

df.iloc[15:26,[1,5]]

     Patient_Name Policy_Type
15   Aditya Mehta        Gold
16  Reyansh Joshi        Gold
17   Vivaan Verma     Premium
18   Pranav Singh       Basic
19      Sai Patel     Premium
20   Vihaan Kumar       Basic
21      Sai Verma     Premium
22   Vihaan Verma    Platinum
23   Aditya Gupta        Gold
24   Pranav Kumar    Platinum
25  Aditya Sharma     Premium

In [143]:
df.loc[15:25,['Patient_Name','Policy_Type']]

## loc ---> location 

#syntax 

#dataframe.loc[range_row, [name of the columns]]

     Patient_Name Policy_Type
15   Aditya Mehta        Gold
16  Reyansh Joshi        Gold
17   Vivaan Verma     Premium
18   Pranav Singh       Basic
19      Sai Patel     Premium
20   Vihaan Kumar       Basic
21      Sai Verma     Premium
22   Vihaan Verma    Platinum
23   Aditya Gupta        Gold
24   Pranav Kumar    Platinum
25  Aditya Sharma     Premium

In [139]:
df

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [141]:
df.loc[45:65,['Patient_Name','Email']]

     Patient_Name                        Email
45  Vivaan Sharma   vivaan.sharma856@gmail.com
46  Krishna Gupta   krishna.gupta187@yahoo.com
47   Vihaan Patel  vihaan.patel412@outlook.com
48    Arjun Verma     arjun.verma648@gmail.com
49   Pranav Joshi  pranav.joshi515@outlook.com
50   Pranav Singh  pranav.singh983@outlook.com
51   Vivaan Reddy    vivaan.reddy408@gmail.com
52   Pranav Gupta    pranav.gupta629@gmail.com
53   Vihaan Verma    vihaan.verma629@yahoo.com
54   Ishaan Singh    ishaan.singh626@gmail.com
55   Vivaan Mehta    vivaan.mehta132@yahoo.com
56  Aditya Sharma   aditya.sharma908@gmail.com
57   Pranav Gupta  pranav.gupta267@outlook.com
58   Vihaan Gupta  vihaan.gupta726@outlook.com
59  Reyansh Singh  reyansh.singh19@outlook.com
60  Krishna Patel   krishna.patel524@yahoo.com
61   Ishaan Yadav  ishaan.yadav693@outlook.com
62   Arjun Sharma  arjun.sharma656@outlook.com
63   Vivaan Gupta     vivaan.gupta69@gmail.com
64   Vivaan Singh    vivaan.singh238@gmail.com
65  Krishna Singh   krishna.singh582@yahoo.com

In [144]:
## rename the columns

df.columns

Index(['Patient_ID', 'Patient_Name', 'Age', 'Email', 'Policy_Number',
       'Policy_Type', 'year'],
      dtype='object')

In [147]:
df.rename(columns={'Age':'Patient_Age'}, inplace=True)

In [148]:
df

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [149]:
df.rename(columns={"Email":"Patient_Email","Policy_Number":"Policy_Num"})

,Patient_ID,Patient_Name,Patient_Age,Patient_Email,Policy_Num,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [ ]:
df.drop(columns=['Patient_ID','year'])

,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type
0,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum
1,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold
2,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum
3,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold
4,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold
...,...,...,...,...,...
995,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic
996,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum
997,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium
998,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium
999,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium

In [155]:
df

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [156]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [159]:
df.set_index('Patient_ID', inplace=True)

In [160]:
df

,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
Patient_ID,,,,,,
1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...
996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [162]:
df.shape

(1000, 6)

In [165]:
df=df.reset_index()

In [166]:
df.shape

(1000, 7)

In [167]:
df.head()

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025

In [178]:
df.sort_values(by='Patient_Age',ascending=False,inplace=True)

In [179]:
df

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
79,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025
807,808,Ishaan Verma,80,ishaan.verma174@yahoo.com,POL142431,Premium,2025
117,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025
74,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025
603,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025
...,...,...,...,...,...,...,...
329,330,Sai Patel,18,sai.patel488@outlook.com,POL933300,Premium,2025
801,802,Arjun Reddy,18,arjun.reddy613@outlook.com,POL716567,Gold,2025
799,800,Reyansh Yadav,18,reyansh.yadav630@outlook.com,POL798658,Platinum,2025
487,488,Aarav Yadav,18,aarav.yadav697@gmail.com,POL228909,Platinum,2025
479,480,Vihaan Joshi,18,vihaan.joshi116@gmail.com,POL880559,Basic,2025

In [ ]:

## get the unique type of policy data has
df['Policy_Type'].unique()

array(['Platinum', 'Premium', 'Gold', 'Basic'], dtype=object)

In [ ]:
## get the number of unique policy data has
df['Policy_Type'].nunique()

4

In [183]:
df['Patient_Age'].unique()

array([80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64,
       63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47,
       46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30,
       29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18], dtype=int64)

In [184]:
df['Patient_Age'].nunique()

63