In [1]:
import pandas as pd

## What is Pandas

Pandas is open-source library that is used for data manupulation and data analysis.

It provide fast, flexiable and expressive data stracture.

It return the data in series or dataframe that is similar to lables , relation , and tabuler data.

In [2]:
## create dataframe from the given dictionary

data = {
    "Name":["Amit","Rahul","Jay","Salman","Katrina","Virat"],
    "Salary":[23000, 56000, 34000,57000,56000,66000],
    "Age":[34,56,45,33,23,32]}

In [3]:
data

{'Name': ['Amit', 'Rahul', 'Jay', 'Salman', 'Katrina', 'Virat'],
 'Salary': [23000, 56000, 34000, 57000, 56000, 66000],
 'Age': [34, 56, 45, 33, 23, 32]}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

      Name  Salary  Age
0     Amit   23000   34
1    Rahul   56000   56
2      Jay   34000   45
3   Salman   57000   33
4  Katrina   56000   23
5    Virat   66000   32

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
## list to dataframe
Fruits = ["Apple","Gauva","Plam","Pomigranad","Blackberry"]
Price=[500,600,400,130,120]

In [8]:
fruits_data = list(zip(Fruits,Price))

In [9]:
fruits_data

[('Apple', 500),
 ('Gauva', 600),
 ('Plam', 400),
 ('Pomigranad', 130),
 ('Blackberry', 120)]

In [10]:
df1= pd.DataFrame(fruits_data, columns= ['Fruits','Price'])

In [11]:
df1

       Fruits  Price
0       Apple    500
1       Gauva    600
2        Plam    400
3  Pomigranad    130
4  Blackberry    120

In [12]:
## empty dataframe
df3 = pd.DataFrame()

In [13]:
type(df3)

pandas.core.frame.DataFrame

In [14]:
df3

Empty DataFrame
Columns: []
Index: []

In [15]:
df3['Fruits'] = Fruits
df3['Price']=Price

In [16]:
df3

       Fruits  Price
0       Apple    500
1       Gauva    600
2        Plam    400
3  Pomigranad    130
4  Blackberry    120

In [17]:
## function that will take n number of list to create dataframe out of that
import logging

logging.basicConfig(level=logging.INFO)

def list_to_dataframe(*lists): ## 3 list of 5 length  ### case 2 --> 3 list 5,4,5
    try:
        length_iterator = list(map(lambda x : len(x),lists)) # [5,5,5] , ##[5,4,5] -->[5,4]
        
        logging.info(f"length of each list  is length_iterator = {length_iterator}")
        
        x = set(length_iterator) # [4,4,4] --> {4}
        logging.info(f"length of x after removing the duplicate x= {x}")
        
        if len(x)!=1:
            raise ValueError("length of the given list is not same")
        else:
            data=list(zip(*lists))
            logging.info(f"here is your data after zipping{data}")
            result = pd.DataFrame(data)
        return result
    except Exception as e:
        logging.error({"type":"error", "info":str(e)})

In [18]:
## pass three list parameter and convert that into data frame

name= ["Rahul","Sanjeev","Sharma","Avinav"]
age = [20,24,56,45]
salary = [56000, 45000, 340000, 67000]

df4=list_to_dataframe(name,age,salary)

INFO:root:length of each list  is length_iterator = [4, 4, 4]
INFO:root:length of x after removing the duplicate x= {4}
INFO:root:here is your data after zipping[('Rahul', 20, 56000), ('Sanjeev', 24, 45000), ('Sharma', 56, 340000), ('Avinav', 45, 67000)]

In [19]:
df4.columns= ['name','age','Salary']

In [20]:
df4

      name  age  Salary
0    Rahul   20   56000
1  Sanjeev   24   45000
2   Sharma   56  340000
3   Avinav   45   67000

In [21]:
## read the data from excel

patient_file_path= r"C:\Users\prash\Desktop\Python_for_all_YT_Playlist\data\patients_data.xlsx"

patient_data = pd.read_excel(patient_file_path)

In [22]:
patient_data

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [23]:
excel_file= pd.ExcelFile(patient_file_path)

In [24]:
excel_file.sheet_names

['Patients_2025', 'Patients_2026']

In [25]:
Patients_2025_date = pd.read_excel(excel_file,sheet_name= 'Patients_2025')

In [26]:
Patients_2026_date = pd.read_excel(excel_file,sheet_name= 'Patients_2026')

In [27]:
Patients_2025_date

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [28]:
Patients_2026_date

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,Year
0,1001,Aarav Mehta,78,aarav.mehta384@yahoo.com,POL625423,Premium,2026
1,1002,Aarav Verma,32,aarav.verma271@yahoo.com,POL930599,Basic,2026
2,1003,Vihaan Verma,40,vihaan.verma345@outlook.com,POL456865,Platinum,2026
3,1004,Aditya Mehta,18,aditya.mehta579@outlook.com,POL982259,Platinum,2026
4,1005,Aarav Singh,39,aarav.singh126@outlook.com,POL742545,Basic,2026
...,...,...,...,...,...,...,...
995,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026
996,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026
997,1998,Aarav Sharma,72,aarav.sharma12@yahoo.com,POL362369,Platinum,2026
998,1999,Ishaan Joshi,65,ishaan.joshi92@outlook.com,POL921223,Premium,2026
999,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026

In [29]:
## read the data from the csv 

csv_file_path = r"C:\Users\prash\Desktop\Python_for_all_YT_Playlist\data\patients_data.csv"

csv_data = pd.read_csv(csv_file_path)

In [30]:
csv_data

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type
0,1,Aditya Reddy,60,aditya.reddy437@outlook.com,POL701385,Gold
1,2,Aditya Verma,69,aditya.verma669@outlook.com,POL908515,Gold
2,3,Vivaan Reddy,58,vivaan.reddy696@yahoo.com,POL098395,Basic
3,4,Sai Gupta,76,sai.gupta699@gmail.com,POL802266,Basic
4,5,Ishaan Mehta,77,ishaan.mehta156@outlook.com,POL423233,Gold
...,...,...,...,...,...,...
995,996,Aditya Verma,41,aditya.verma839@yahoo.com,POL265181,Platinum
996,997,Aarav Gupta,63,aarav.gupta900@gmail.com,POL797105,Platinum
997,998,Vivaan Gupta,40,vivaan.gupta159@gmail.com,POL713191,Gold
998,999,Ishaan Verma,45,ishaan.verma817@gmail.com,POL146295,Basic
999,1000,Vihaan Patel,35,vihaan.patel222@yahoo.com,POL144496,Premium

In [31]:
## read the data from json

json_file_path=r"C:\Users\prash\Desktop\Python_for_all_YT_Playlist\data\patients_data.json"

pd.read_json(json_file_path)

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type
0,1,Aditya Reddy,60,aditya.reddy437@outlook.com,POL701385,Gold
1,2,Aditya Verma,69,aditya.verma669@outlook.com,POL908515,Gold
2,3,Vivaan Reddy,58,vivaan.reddy696@yahoo.com,POL098395,Basic
3,4,Sai Gupta,76,sai.gupta699@gmail.com,POL802266,Basic
4,5,Ishaan Mehta,77,ishaan.mehta156@outlook.com,POL423233,Gold
...,...,...,...,...,...,...
995,996,Aditya Verma,41,aditya.verma839@yahoo.com,POL265181,Platinum
996,997,Aarav Gupta,63,aarav.gupta900@gmail.com,POL797105,Platinum
997,998,Vivaan Gupta,40,vivaan.gupta159@gmail.com,POL713191,Gold
998,999,Ishaan Verma,45,ishaan.verma817@gmail.com,POL146295,Basic
999,1000,Vihaan Patel,35,vihaan.patel222@yahoo.com,POL144496,Premium

1. dict
2. list
3. Custom function to read data from n list
4. Excel file , sheet specific
5. CSV
6. Json

In [32]:
df =Patients_2025_date

In [33]:
df

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [34]:
## how mnay rows and columns do we have

df.shape

(1000, 7)

In [35]:
df.size

7000

In [36]:
## data types and over all view of the data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Patient_ID     1000 non-null   int64
 1   Patient_Name   1000 non-null   object
 2   Age            1000 non-null   int64
 3   Email          1000 non-null   object
 4   Policy_Number  1000 non-null   object
 5   Policy_Type    1000 non-null   object
 6   year           1000 non-null   int64
dtypes: int64(3), object(4)
memory usage: 54.8+ KB

In [37]:
## i want to see top 5 records
df.head()

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025

In [38]:
## only bottom 5 records

df.tail()

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [39]:
## I want to see 20 records from the top

df.head(20)

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
5,6,Aditya Gupta,33,aditya.gupta574@yahoo.com,POL350037,Basic,2025
6,7,Vihaan Patel,56,vihaan.patel300@outlook.com,POL986252,Basic,2025
7,8,Aditya Yadav,53,aditya.yadav682@outlook.com,POL341551,Platinum,2025
8,9,Sai Yadav,45,sai.yadav975@gmail.com,POL440267,Gold,2025
9,10,Aditya Sharma,23,aditya.sharma396@gmail.com,POL938553,Gold,2025
10,11,Reyansh Yadav,69,reyansh.yadav432@gmail.com,POL676644,Gold,2025
11,12,Pranav Singh,30,pranav.singh95@yahoo.com,POL698348,Gold,2025
12,13,Ishaan Singh,23,ishaan.singh184@gmail.com,POL286469,Platinum,2025
13,14,Sai Kumar,35,sai.kumar179@gmail.com,POL701515,Platinum,2025
14,15,Ishaan Gupta,58,ishaan.gupta374@yahoo.com,POL069482,Platinum,2025
15,16,Aditya Mehta,38,aditya.mehta885@gmail.com,POL028707,Gold,2025
16,17,Reyansh Joshi,22,reyansh.joshi145@outlook.com,POL344833,Gold,2025
17,18,Vivaan Verma,44,vivaan.verma358@gmail.com,POL079916,Premium,2025
18,19,Pranav Singh,53,pranav.singh399@gmail.com,POL412488,Basic,2025
19,20,Sai Patel,52,sai.patel760@gmail.com,POL188458,Premium,2025

In [40]:
df.tail(25)

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
975,976,Reyansh Patel,28,reyansh.patel62@outlook.com,POL511704,Premium,2025
976,977,Krishna Sharma,36,krishna.sharma255@gmail.com,POL906950,Basic,2025
977,978,Vivaan Yadav,44,vivaan.yadav183@gmail.com,POL725642,Basic,2025
978,979,Reyansh Yadav,48,reyansh.yadav654@gmail.com,POL736990,Basic,2025
979,980,Vihaan Gupta,29,vihaan.gupta880@outlook.com,POL038984,Premium,2025
980,981,Aarav Reddy,39,aarav.reddy441@gmail.com,POL400447,Premium,2025
981,982,Vivaan Reddy,18,vivaan.reddy710@yahoo.com,POL831541,Gold,2025
982,983,Reyansh Patel,20,reyansh.patel789@gmail.com,POL976549,Basic,2025
983,984,Aditya Reddy,56,aditya.reddy409@gmail.com,POL219318,Gold,2025
984,985,Sai Mehta,74,sai.mehta51@outlook.com,POL829079,Basic,2025
985,986,Vivaan Reddy,35,vivaan.reddy717@outlook.com,POL024632,Basic,2025
986,987,Krishna Singh,42,krishna.singh24@outlook.com,POL268940,Basic,2025
987,988,Reyansh Verma,30,reyansh.verma743@outlook.com,POL966448,Basic,2025
988,989,Sai Reddy,28,sai.reddy786@yahoo.com,POL109584,Premium,2025
989,990,Ishaan Singh,36,ishaan.singh103@yahoo.com,POL585250,Premium,2025
990,991,Aarav Kumar,34,aarav.kumar294@outlook.com,POL694930,Gold,2025
991,992,Sai Reddy,62,sai.reddy600@outlook.com,POL079714,Basic,2025
992,993,Vivaan Mehta,23,vivaan.mehta928@yahoo.com,POL486384,Premium,2025
993,994,Pranav Mehta,77,pranav.mehta919@yahoo.com,POL065312,Premium,2025
994,995,Aarav Yadav,66,aarav.yadav625@yahoo.com,POL304066,Basic,2025
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [41]:
## I want only columns name

df.columns

Index(['Patient_ID', 'Patient_Name', 'Age', 'Email', 'Policy_Number',
       'Policy_Type', 'year'],
      dtype='object')

In [42]:
df.describe()

        Patient_ID          Age    year
count  1000.000000  1000.000000  1000.0
mean    500.500000    48.075000  2025.0
std     288.819436    18.360296     0.0
min       1.000000    18.000000  2025.0
25%     250.750000    32.000000  2025.0
50%     500.500000    48.000000  2025.0
75%     750.250000    63.000000  2025.0
max    1000.000000    80.000000  2025.0

In [43]:
type(df.Age)

pandas.core.series.Series

## Series: 


We have discussed about the dataframe but we have not discussed about the series

### What is series

Aseries in pandas is one dimensional labeled array.

It has two main part value and index(lables)

In [44]:
Fruits

['Apple', 'Gauva', 'Plam', 'Pomigranad', 'Blackberry']

In [45]:
Price.append(30)

In [46]:
Price

[500, 600, 400, 130, 120, 30]

In [47]:
age.append(20)

In [48]:
age

[20, 24, 56, 45, 20]

In [49]:
name

['Rahul', 'Sanjeev', 'Sharma', 'Avinav']

In [50]:
salary

[56000, 45000, 340000, 67000]

In [51]:
age=age[0:4]

In [52]:
age

[20, 24, 56, 45]

In [53]:
df

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [54]:
## i want to get only one column

df.Age

0      22
1      40
2      51
3      36
4      23
       ..
995    32
996    67
997    27
998    49
999    72
Name: Age, Length: 1000, dtype: int64

In [55]:
type(df[['Age']])

pandas.core.frame.DataFrame

In [56]:
df['Age']

0      22
1      40
2      51
3      36
4      23
       ..
995    32
996    67
997    27
998    49
999    72
Name: Age, Length: 1000, dtype: int64

In [57]:
df.columns

Index(['Patient_ID', 'Patient_Name', 'Age', 'Email', 'Policy_Number',
       'Policy_Type', 'year'],
      dtype='object')

In [58]:
df[['Patient_Name','Age','Policy_Number']]

      Patient_Name  Age Policy_Number
0    Krishna Reddy   22     POL602544
1      Arjun Gupta   40     POL856642
2     Vivaan Singh   51     POL512045
3      Arjun Kumar   36     POL132724
4    Krishna Verma   23     POL060110
..             ...  ...           ...
995   Vivaan Verma   32     POL973107
996    Arjun Mehta   67     POL755200
997  Krishna Gupta   27     POL970351
998   Pranav Verma   49     POL343885
999  Reyansh Patel   72     POL418617

[1000 rows x 3 columns]

In [59]:
df

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [60]:
## get all the columns along with 20 to 30 rowns numbers

df.iloc[20:31,:] ## iloc -- index location 

## syntax of iloc is 

#dataframe.iloc[range_rows, range_columns]

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
20,21,Vihaan Kumar,73,vihaan.kumar651@outlook.com,POL996694,Basic,2025
21,22,Sai Verma,60,sai.verma422@outlook.com,POL752117,Premium,2025
22,23,Vihaan Verma,43,vihaan.verma972@outlook.com,POL926834,Platinum,2025
23,24,Aditya Gupta,37,aditya.gupta843@yahoo.com,POL722573,Gold,2025
24,25,Pranav Kumar,25,pranav.kumar649@yahoo.com,POL542704,Platinum,2025
25,26,Aditya Sharma,61,aditya.sharma1@outlook.com,POL352573,Premium,2025
26,27,Arjun Kumar,43,arjun.kumar396@outlook.com,POL806142,Premium,2025
27,28,Arjun Joshi,70,arjun.joshi601@gmail.com,POL331281,Platinum,2025
28,29,Aditya Joshi,41,aditya.joshi111@yahoo.com,POL065819,Gold,2025
29,30,Vivaan Patel,44,vivaan.patel698@outlook.com,POL492011,Gold,2025
30,31,Reyansh Sharma,48,reyansh.sharma154@outlook.com,POL492841,Gold,2025

In [61]:
## get records from 15 to 25 index for column --> Patient_name , Policy_Type

df.iloc[15:26,[1,5]]

     Patient_Name Policy_Type
15   Aditya Mehta        Gold
16  Reyansh Joshi        Gold
17   Vivaan Verma     Premium
18   Pranav Singh       Basic
19      Sai Patel     Premium
20   Vihaan Kumar       Basic
21      Sai Verma     Premium
22   Vihaan Verma    Platinum
23   Aditya Gupta        Gold
24   Pranav Kumar    Platinum
25  Aditya Sharma     Premium

In [62]:
df.loc[15:25,['Patient_Name','Policy_Type']]

## loc ---> location 

#syntax 

#dataframe.loc[range_row, [name of the columns]]

     Patient_Name Policy_Type
15   Aditya Mehta        Gold
16  Reyansh Joshi        Gold
17   Vivaan Verma     Premium
18   Pranav Singh       Basic
19      Sai Patel     Premium
20   Vihaan Kumar       Basic
21      Sai Verma     Premium
22   Vihaan Verma    Platinum
23   Aditya Gupta        Gold
24   Pranav Kumar    Platinum
25  Aditya Sharma     Premium

In [63]:
df

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [64]:
df.loc[45:65,['Patient_Name','Email']]

     Patient_Name                        Email
45  Vivaan Sharma   vivaan.sharma856@gmail.com
46  Krishna Gupta   krishna.gupta187@yahoo.com
47   Vihaan Patel  vihaan.patel412@outlook.com
48    Arjun Verma     arjun.verma648@gmail.com
49   Pranav Joshi  pranav.joshi515@outlook.com
50   Pranav Singh  pranav.singh983@outlook.com
51   Vivaan Reddy    vivaan.reddy408@gmail.com
52   Pranav Gupta    pranav.gupta629@gmail.com
53   Vihaan Verma    vihaan.verma629@yahoo.com
54   Ishaan Singh    ishaan.singh626@gmail.com
55   Vivaan Mehta    vivaan.mehta132@yahoo.com
56  Aditya Sharma   aditya.sharma908@gmail.com
57   Pranav Gupta  pranav.gupta267@outlook.com
58   Vihaan Gupta  vihaan.gupta726@outlook.com
59  Reyansh Singh  reyansh.singh19@outlook.com
60  Krishna Patel   krishna.patel524@yahoo.com
61   Ishaan Yadav  ishaan.yadav693@outlook.com
62   Arjun Sharma  arjun.sharma656@outlook.com
63   Vivaan Gupta     vivaan.gupta69@gmail.com
64   Vivaan Singh    vivaan.singh238@gmail.com
65  Krishna Singh   krishna.singh582@yahoo.com

In [65]:
## rename the columns

df.columns

Index(['Patient_ID', 'Patient_Name', 'Age', 'Email', 'Policy_Number',
       'Policy_Type', 'year'],
      dtype='object')

In [66]:
df.rename(columns={'Age':'Patient_Age'}, inplace=True)

In [67]:
df

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [68]:
df.rename(columns={"Email":"Patient_Email","Policy_Number":"Policy_Num"})

,Patient_ID,Patient_Name,Patient_Age,Patient_Email,Policy_Num,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [69]:
df.drop(columns=['Patient_ID','year'])

,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type
0,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum
1,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold
2,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum
3,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold
4,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold
...,...,...,...,...,...
995,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic
996,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum
997,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium
998,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium
999,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium

In [70]:
df

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...,...
995,996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
996,997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
997,998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
998,999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
999,1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [71]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [72]:
df.set_index('Patient_ID', inplace=True)

In [73]:
df

,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
Patient_ID,,,,,,
1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025
...,...,...,...,...,...,...
996,Vivaan Verma,32,vivaan.verma316@gmail.com,POL973107,Basic,2025
997,Arjun Mehta,67,arjun.mehta768@outlook.com,POL755200,Platinum,2025
998,Krishna Gupta,27,krishna.gupta488@outlook.com,POL970351,Premium,2025
999,Pranav Verma,49,pranav.verma36@yahoo.com,POL343885,Premium,2025
1000,Reyansh Patel,72,reyansh.patel612@yahoo.com,POL418617,Premium,2025

In [74]:
df.shape

(1000, 6)

In [75]:
df=df.reset_index()

In [76]:
df.shape

(1000, 7)

In [77]:
df.head()

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
0,1,Krishna Reddy,22,krishna.reddy835@outlook.com,POL602544,Platinum,2025
1,2,Arjun Gupta,40,arjun.gupta570@outlook.com,POL856642,Gold,2025
2,3,Vivaan Singh,51,vivaan.singh72@yahoo.com,POL512045,Platinum,2025
3,4,Arjun Kumar,36,arjun.kumar883@outlook.com,POL132724,Gold,2025
4,5,Krishna Verma,23,krishna.verma273@yahoo.com,POL060110,Gold,2025

In [78]:
df.sort_values(by='Patient_Age',ascending=False,inplace=True)

In [79]:
df

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
79,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025
117,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025
74,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025
603,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025
590,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025
...,...,...,...,...,...,...,...
329,330,Sai Patel,18,sai.patel488@outlook.com,POL933300,Premium,2025
801,802,Arjun Reddy,18,arjun.reddy613@outlook.com,POL716567,Gold,2025
799,800,Reyansh Yadav,18,reyansh.yadav630@outlook.com,POL798658,Platinum,2025
263,264,Sai Patel,18,sai.patel677@gmail.com,POL648119,Premium,2025
479,480,Vihaan Joshi,18,vihaan.joshi116@gmail.com,POL880559,Basic,2025

In [80]:

## get the unique type of policy data has
df['Policy_Type'].unique()

array(['Platinum', 'Premium', 'Gold', 'Basic'], dtype=object)

In [81]:
## get the number of unique policy data has
df['Policy_Type'].nunique()

4

In [82]:
df['Patient_Age'].unique()

array([80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64,
       63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47,
       46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30,
       29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18], dtype=int64)

In [83]:
df['Patient_Age'].nunique()

63

In [84]:
df

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
79,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025
117,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025
74,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025
603,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025
590,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025
...,...,...,...,...,...,...,...
329,330,Sai Patel,18,sai.patel488@outlook.com,POL933300,Premium,2025
801,802,Arjun Reddy,18,arjun.reddy613@outlook.com,POL716567,Gold,2025
799,800,Reyansh Yadav,18,reyansh.yadav630@outlook.com,POL798658,Platinum,2025
263,264,Sai Patel,18,sai.patel677@gmail.com,POL648119,Premium,2025
479,480,Vihaan Joshi,18,vihaan.joshi116@gmail.com,POL880559,Basic,2025

In [85]:
Patients_2026_date

,Patient_ID,Patient_Name,Age,Email,Policy_Number,Policy_Type,Year
0,1001,Aarav Mehta,78,aarav.mehta384@yahoo.com,POL625423,Premium,2026
1,1002,Aarav Verma,32,aarav.verma271@yahoo.com,POL930599,Basic,2026
2,1003,Vihaan Verma,40,vihaan.verma345@outlook.com,POL456865,Platinum,2026
3,1004,Aditya Mehta,18,aditya.mehta579@outlook.com,POL982259,Platinum,2026
4,1005,Aarav Singh,39,aarav.singh126@outlook.com,POL742545,Basic,2026
...,...,...,...,...,...,...,...
995,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026
996,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026
997,1998,Aarav Sharma,72,aarav.sharma12@yahoo.com,POL362369,Platinum,2026
998,1999,Ishaan Joshi,65,ishaan.joshi92@outlook.com,POL921223,Premium,2026
999,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026

In [86]:
pd.concat([df,Patients_2026_date])

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Age,Year
79,80,Krishna Kumar,80.0,krishna.kumar274@yahoo.com,POL078226,Platinum,2025.0,NaN,NaN
117,118,Sai Yadav,80.0,sai.yadav586@gmail.com,POL034543,Platinum,2025.0,NaN,NaN
74,75,Sai Joshi,80.0,sai.joshi804@outlook.com,POL875971,Premium,2025.0,NaN,NaN
603,604,Pranav Patel,80.0,pranav.patel329@yahoo.com,POL097005,Premium,2025.0,NaN,NaN
590,591,Sai Reddy,80.0,sai.reddy717@yahoo.com,POL640591,Premium,2025.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
995,1996,Aarav Mehta,NaN,aarav.mehta63@outlook.com,POL748260,Premium,NaN,31.0,2026.0
996,1997,Ishaan Yadav,NaN,ishaan.yadav830@outlook.com,POL725846,Basic,NaN,59.0,2026.0
997,1998,Aarav Sharma,NaN,aarav.sharma12@yahoo.com,POL362369,Platinum,NaN,72.0,2026.0
998,1999,Ishaan Joshi,NaN,ishaan.joshi92@outlook.com,POL921223,Premium,NaN,65.0,2026.0
999,2000,Vivaan Singh,NaN,vivaan.singh214@yahoo.com,POL309917,Platinum,NaN,57.0,2026.0

In [87]:
df.columns

Index(['Patient_ID', 'Patient_Name', 'Patient_Age', 'Email', 'Policy_Number',
       'Policy_Type', 'year'],
      dtype='object')

In [88]:
Patients_2026_date.columns

Index(['Patient_ID', 'Patient_Name', 'Age', 'Email', 'Policy_Number',
       'Policy_Type', 'Year'],
      dtype='object')

In [89]:
Patients_2026_date.rename(columns={'Age':'Patient_Age','Year':'year'}, inplace=True)

In [90]:
Patients_2026_date.columns

Index(['Patient_ID', 'Patient_Name', 'Patient_Age', 'Email', 'Policy_Number',
       'Policy_Type', 'year'],
      dtype='object')

In [91]:
patient_data=pd.concat([df,Patients_2026_date],axis=0)

In [92]:
patient_data.shape

(2000, 7)

In [93]:
patient_data.reset_index(inplace=True)

In [94]:
patient_data.head()

,index,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
0,79,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025
1,117,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025
2,74,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025
3,603,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025
4,590,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025

In [95]:
## drop the column index

patient_data.drop(columns='index', inplace=True)

In [96]:
patient_data.head()

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year
0,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025
1,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025
2,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025
3,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025
4,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025

In [97]:
policy_file_path = r"C:\Users\prash\Desktop\Python_for_all_YT_Playlist\data\policy_data.xlsx"

In [98]:
policy_data= pd.read_excel(policy_file_path)

In [99]:
policy_data.shape

(2000, 4)

In [100]:
policy_data

     Policy_Number        Provider_Name  Coverage_Amount  Start_Year
0        POL602544  New India Assurance           586130        2025
1        POL856642             Max Bupa           216864        2024
2        POL512045  New India Assurance           218977        2025
3        POL132724             Max Bupa           842430        2025
4        POL060110          Star Health           806879        2025
...            ...                  ...              ...         ...
1995     POL748260          Star Health           484092        2024
1996     POL725846          Star Health           579515        2023
1997     POL362369             Max Bupa           644437        2023
1998     POL921223             Max Bupa           965221        2024
1999     POL309917        ICICI Lombard           213392        2024

[2000 rows x 4 columns]

In [101]:
##pd.concat([patient_data,policy_data],axis=1)# you can't use cancatination on relational data. beciase cancat perform based on index match

In [102]:
## Merge

patient_data.merge(policy_data,how='left',on='Policy_Number')

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
0,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026
1,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023
2,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025
3,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026
4,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026
...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023
1999,1998,Aarav Sharma,72,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023
2000,1999,Ishaan Joshi,65,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024

In [103]:
## case 2 -- if both the data fame common columns name is not same, what ypu will do in this case?

In [104]:
policy_data.rename(columns ={'Policy_Number':'policy_number'},inplace=True)

In [105]:
policy_data.head()

  policy_number        Provider_Name  Coverage_Amount  Start_Year
0     POL602544  New India Assurance           586130        2025
1     POL856642             Max Bupa           216864        2024
2     POL512045  New India Assurance           218977        2025
3     POL132724             Max Bupa           842430        2025
4     POL060110          Star Health           806879        2025

In [106]:
patient_data=patient_data.merge(policy_data,how='left',left_on='Policy_Number',right_on='policy_number')

In [107]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,policy_number,Provider_Name,Coverage_Amount,Start_Year
0,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,POL078226,HDFC Ergo,851420,2026
1,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025,POL034543,Star Health,829205,2023
2,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025,POL875971,Star Health,659481,2025
3,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025,POL097005,HDFC Ergo,135569,2026
4,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025,POL640591,HDFC Ergo,954316,2026
...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,POL748260,Star Health,484092,2024
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,POL725846,Star Health,579515,2023
1999,1998,Aarav Sharma,72,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,POL362369,Max Bupa,644437,2023
2000,1999,Ishaan Joshi,65,ishaan.joshi92@outlook.com,POL921223,Premium,2026,POL921223,Max Bupa,965221,2024
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,POL309917,ICICI Lombard,213392,2024

In [108]:
patient_data.drop(columns={'policy_number'}, inplace=True)

In [109]:
patient_data.head()

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
0,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026
1,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023
2,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025
3,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026
4,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026

In [110]:
patient_data.shape

(2002, 10)

In [111]:
## filter out patient data where policy type is basic

patient_data[patient_data["Policy_Type"]=="Basic"]

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
17,340,Ishaan Kumar,79,ishaan.kumar451@outlook.com,POL875129,Basic,2025,New India Assurance,233949,2023
23,388,Arjun Reddy,79,arjun.reddy866@yahoo.com,POL969961,Basic,2025,New India Assurance,139882,2026
25,295,Ishaan Gupta,79,ishaan.gupta980@outlook.com,POL998592,Basic,2025,HDFC Ergo,462365,2026
30,384,Aarav Singh,78,aarav.singh557@yahoo.com,POL052224,Basic,2025,Max Bupa,661113,2023
31,173,Krishna Yadav,78,krishna.yadav117@outlook.com,POL983399,Basic,2025,Star Health,499119,2024
...,...,...,...,...,...,...,...,...,...,...
1978,1977,Vivaan Singh,43,vivaan.singh140@gmail.com,POL977361,Basic,2026,Max Bupa,608881,2023
1979,1978,Vivaan Patel,56,vivaan.patel152@gmail.com,POL494521,Basic,2026,ICICI Lombard,179532,2025
1994,1993,Pranav Mehta,66,pranav.mehta382@yahoo.com,POL404097,Basic,2026,New India Assurance,433539,2026
1996,1995,Reyansh Joshi,52,reyansh.joshi728@gmail.com,POL974359,Basic,2026,Star Health,808307,2026
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023

In [112]:
## how many patient above 40 has taken policy from ICICI Lombard
patient_data[(patient_data['Patient_Age']>40) & (patient_data['Provider_Name']=='ICICI Lombard')  ].count()

Patient_ID         270
Patient_Name       270
Patient_Age        270
Email              270
Policy_Number      270
Policy_Type        270
year               270
Provider_Name      270
Coverage_Amount    270
Start_Year         270
dtype: int64

In [113]:
## how many patient above age 50 taken insurence from Icici or HDFC

patient_data[(patient_data['Patient_Age']>50) & 
             ((patient_data['Provider_Name']=='ICICI Lombard') | 
              (patient_data['Provider_Name']=='HDFC Ergo'))  ].count()

Patient_ID         379
Patient_Name       379
Patient_Age        379
Email              379
Policy_Number      379
Policy_Type        379
year               379
Provider_Name      379
Coverage_Amount    379
Start_Year         379
dtype: int64

In [114]:
## how many patient has invested amount b/w 200000 to 400000 during year 2023 and 2024 in insurence
    
patient_data[(patient_data['Coverage_Amount'].between(200000, 400000)) & (patient_data['Start_Year'].isin([2023,2024]))]['Patient_ID'].count()

248

In [115]:
## how to find there is duplicate in the data or not 

patient_data['Patient_ID'].value_counts()

Patient_ID
1173    2
1581    2
1330    1
1342    1
1341    1
       ..
24      1
353     1
176     1
895     1
2000    1
Name: count, Length: 2000, dtype: int64

In [116]:
patient_data[patient_data['Patient_ID'].isin([1173,1581])]

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
1172,1173,Krishna Mehta,59,krishna.mehta687@outlook.com,POL071964,Premium,2026,HDFC Ergo,169951,2023
1173,1173,Krishna Mehta,59,krishna.mehta687@outlook.com,POL071964,Premium,2026,Max Bupa,718566,2025
1581,1581,Aditya Patel,31,aditya.patel676@yahoo.com,POL071964,Premium,2026,HDFC Ergo,169951,2023
1582,1581,Aditya Patel,31,aditya.patel676@yahoo.com,POL071964,Premium,2026,Max Bupa,718566,2025

In [117]:
patient_data.drop_duplicates(subset='Patient_ID',keep='first', inplace=True)

In [118]:
patient_data['Patient_ID'].duplicated().sum()

0

In [119]:
patient_data['Coverage_Amount'].unique()

array([851420, 829205, 659481, ..., 644437, 965221, 213392], dtype=int64)

In [120]:
## how many patient has invested amount b/w 200000 to 400000 during year 2023 and 2024 in insurence
    
patient_data[(patient_data['Coverage_Amount'].between(200000, 400000)) & (patient_data['Start_Year'].isin([2023,2024]))]['Patient_ID'].count()

248

In [121]:
patient_data.head()

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
0,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026
1,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023
2,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025
3,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026
4,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026

In [122]:
patient_data.query("Coverage_Amount.between(200000,400000) and Start_Year.isin([2023,2024])")

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
12,471,Aditya Reddy,80,aditya.reddy246@outlook.com,POL002244,Premium,2025,New India Assurance,225178,2024
16,147,Aditya Kumar,79,aditya.kumar636@gmail.com,POL661178,Premium,2025,Star Health,250001,2024
17,340,Ishaan Kumar,79,ishaan.kumar451@outlook.com,POL875129,Basic,2025,New India Assurance,233949,2023
18,218,Vivaan Gupta,79,vivaan.gupta585@outlook.com,POL417947,Premium,2025,ICICI Lombard,251984,2024
20,635,Aarav Gupta,79,aarav.gupta587@outlook.com,POL601615,Premium,2025,ICICI Lombard,286495,2023
...,...,...,...,...,...,...,...,...,...,...
1958,1957,Pranav Gupta,60,pranav.gupta933@yahoo.com,POL051677,Platinum,2026,ICICI Lombard,280601,2024
1959,1958,Vihaan Patel,39,vihaan.patel448@yahoo.com,POL767928,Premium,2026,New India Assurance,366571,2024
1960,1959,Reyansh Gupta,74,reyansh.gupta307@outlook.com,POL176237,Premium,2026,New India Assurance,221417,2024
1993,1992,Aarav Singh,71,aarav.singh994@gmail.com,POL516802,Gold,2026,Max Bupa,391599,2023
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024

In [123]:
## filter out patient details whos age is grater than 40 and taken Premium policy

patient_data.query("Patient_Age>40 and Policy_Type == 'Premium'" )

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
2,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025
3,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026
4,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026
7,71,Sai Sharma,80,sai.sharma866@yahoo.com,POL959347,Premium,2025,HDFC Ergo,192275,2023
8,808,Ishaan Verma,80,ishaan.verma174@yahoo.com,POL142431,Premium,2025,Star Health,697889,2025
...,...,...,...,...,...,...,...,...,...,...
1980,1979,Sai Singh,60,sai.singh449@outlook.com,POL264035,Premium,2026,Star Health,407515,2023
1982,1981,Sai Verma,79,sai.verma933@gmail.com,POL355570,Premium,2026,Star Health,325225,2026
1986,1985,Vihaan Mehta,80,vihaan.mehta18@yahoo.com,POL315115,Premium,2026,Star Health,404580,2025
1991,1990,Krishna Yadav,49,krishna.yadav340@yahoo.com,POL193513,Premium,2026,Star Health,327837,2026
2000,1999,Ishaan Joshi,65,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024

In [124]:
## how many patient email id contains gmail.com

patient_data[patient_data["Email"].str.contains('gmail.com')]['Patient_ID'].count()

632

In [125]:
## how many patients email start with AR
patient_data[patient_data["Email"].str.startswith('ar')]

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
23,388,Arjun Reddy,79,arjun.reddy866@yahoo.com,POL969961,Basic,2025,New India Assurance,139882,2026
32,568,Arjun Singh,78,arjun.singh955@gmail.com,POL988578,Platinum,2025,ICICI Lombard,174414,2025
47,823,Arjun Sharma,77,arjun.sharma553@outlook.com,POL874859,Gold,2025,New India Assurance,490751,2025
65,815,Arjun Yadav,76,arjun.yadav841@yahoo.com,POL416212,Basic,2025,Star Health,654354,2026
74,766,Arjun Joshi,76,arjun.joshi809@yahoo.com,POL052123,Premium,2025,ICICI Lombard,765996,2024
...,...,...,...,...,...,...,...,...,...,...
1936,1935,Arjun Joshi,41,arjun.joshi408@gmail.com,POL225042,Premium,2026,HDFC Ergo,848511,2023
1939,1938,Arjun Patel,51,arjun.patel163@yahoo.com,POL738550,Basic,2026,ICICI Lombard,153196,2024
1940,1939,Arjun Yadav,55,arjun.yadav996@yahoo.com,POL637784,Premium,2026,Max Bupa,388956,2023
1963,1962,Arjun Singh,76,arjun.singh26@gmail.com,POL236310,Basic,2026,New India Assurance,600302,2025
1992,1991,Arjun Mehta,77,arjun.mehta725@yahoo.com,POL660313,Platinum,2026,HDFC Ergo,659064,2024

In [126]:
patient_data[patient_data["Email"].str.startswith('ar')]['Patient_ID'].count()

190

In [127]:
## how many patient last name end with Singh
patient_data[patient_data["Patient_Name"].str.endswith('Singh')]

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
5,825,Aditya Singh,80,aditya.singh435@outlook.com,POL833209,Gold,2025,ICICI Lombard,471813,2026
27,99,Aditya Singh,79,aditya.singh601@yahoo.com,POL276431,Premium,2025,Star Health,271490,2023
29,502,Vihaan Singh,79,vihaan.singh558@gmail.com,POL053549,Platinum,2025,HDFC Ergo,512566,2024
30,384,Aarav Singh,78,aarav.singh557@yahoo.com,POL052224,Basic,2025,Max Bupa,661113,2023
32,568,Arjun Singh,78,arjun.singh955@gmail.com,POL988578,Platinum,2025,ICICI Lombard,174414,2025
...,...,...,...,...,...,...,...,...,...,...
1978,1977,Vivaan Singh,43,vivaan.singh140@gmail.com,POL977361,Basic,2026,Max Bupa,608881,2023
1980,1979,Sai Singh,60,sai.singh449@outlook.com,POL264035,Premium,2026,Star Health,407515,2023
1988,1987,Aditya Singh,26,aditya.singh106@yahoo.com,POL367519,Platinum,2026,New India Assurance,408275,2024
1993,1992,Aarav Singh,71,aarav.singh994@gmail.com,POL516802,Gold,2026,Max Bupa,391599,2023
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024

In [128]:
patient_data[patient_data["Patient_Name"].str.endswith('Singh')]['Patient_ID'].count()

227

where
mask
cut
notnull() 
dropna() 
fillna() 
Apply()
Map() 
Split columns 
strip , lower , upper
Group by
Multiple columns group by
agg function
pivot()
Pivot_tables
stack()
unstack()
crosstab()
Rank()
Rolling window()
Resampling()

In [129]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year
0,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026
1,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023
2,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025
3,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026
4,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026
...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023
1999,1998,Aarav Sharma,72,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023
2000,1999,Ishaan Joshi,65,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024

In [130]:
patient_data["Patient_Age"].unique()

array([80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64,
       63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47,
       46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30,
       29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18], dtype=int64)

## Where 
1.It is used to replace the value where a condition is false
2. Keep the value if condition is True, otherwise replace it.

syntax

df.where(condition,other)

where(condition, value_if_false)

In [131]:
patient_data['Patient_Age_category']=patient_data['Patient_Age'].where(patient_data['Patient_Age']>30 , "Young")

In [132]:
patient_data.sort_values(by='Patient_Age',ascending=True)

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category
999,480,Vihaan Joshi,18,vihaan.joshi116@gmail.com,POL880559,Basic,2025,Max Bupa,358887,2025,Young
983,641,Reyansh Verma,18,reyansh.verma874@outlook.com,POL154666,Premium,2025,Max Bupa,152860,2026,Young
982,79,Reyansh Gupta,18,reyansh.gupta705@outlook.com,POL621080,Basic,2025,Max Bupa,707475,2025,Young
1942,1941,Sai Gupta,18,sai.gupta133@outlook.com,POL234994,Premium,2026,HDFC Ergo,673551,2026,Young
1387,1387,Vihaan Gupta,18,vihaan.gupta357@outlook.com,POL353995,Premium,2026,ICICI Lombard,459559,2025,Young
...,...,...,...,...,...,...,...,...,...,...,...
9,799,Aditya Gupta,80,aditya.gupta892@outlook.com,POL041662,Gold,2025,HDFC Ergo,102853,2024,80
1505,1505,Aarav Patel,80,aarav.patel737@yahoo.com,POL927503,Basic,2026,HDFC Ergo,278967,2025,80
8,808,Ishaan Verma,80,ishaan.verma174@yahoo.com,POL142431,Premium,2025,Star Health,697889,2025,80
1375,1375,Arjun Verma,80,arjun.verma443@outlook.com,POL320208,Platinum,2026,HDFC Ergo,670552,2025,80
0,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,80

In [133]:
patient_data[patient_data['Patient_Age'].isin([18,25,29,31,30,45])]

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category
536,326,Aditya Mehta,45,aditya.mehta365@gmail.com,POL023099,Platinum,2025,Star Health,179205,2026,45
537,659,Aarav Yadav,45,aarav.yadav297@outlook.com,POL739218,Platinum,2025,ICICI Lombard,452061,2024,45
538,9,Sai Yadav,45,sai.yadav975@gmail.com,POL440267,Gold,2025,Max Bupa,972600,2023,45
539,307,Sai Gupta,45,sai.gupta389@outlook.com,POL792165,Premium,2025,ICICI Lombard,415636,2025,45
540,593,Reyansh Gupta,45,reyansh.gupta163@outlook.com,POL647806,Platinum,2025,New India Assurance,893759,2025,45
...,...,...,...,...,...,...,...,...,...,...,...
1942,1941,Sai Gupta,18,sai.gupta133@outlook.com,POL234994,Premium,2026,HDFC Ergo,673551,2026,Young
1949,1948,Pranav Joshi,25,pranav.joshi820@yahoo.com,POL807612,Premium,2026,ICICI Lombard,296760,2024,Young
1954,1953,Aditya Joshi,31,aditya.joshi357@outlook.com,POL859688,Premium,2026,New India Assurance,821254,2026,31
1975,1974,Pranav Gupta,45,pranav.gupta188@outlook.com,POL133432,Premium,2026,ICICI Lombard,420067,2025,45
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,31

## now 
I want to map 

age description 

0 to 29 ---> Young
30 to 49 ---> Middle Age
50 to 60 ---> Early Older

>> 60 ----> Older Age

In [134]:
patient_data['Patient_Age_category']=patient_data['Patient_Age'].where(patient_data['Patient_Age']>30 , "Young").where((patient_data['Patient_Age']>50) |(patient_data['Patient_Age']<30),'Middle Age').where((patient_data['Patient_Age']>60) | (patient_data['Patient_Age']<50),'Early Older').where(patient_data['Patient_Age']<60,"Older Age")

In [135]:
patient_data[patient_data['Patient_Age'].isin([25,26])]

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category
836,356,Arjun Patel,26,arjun.patel474@gmail.com,POL352483,Gold,2025,ICICI Lombard,222480,2024,Young
837,355,Vivaan Patel,26,vivaan.patel766@outlook.com,POL045762,Premium,2025,Star Health,644766,2024,Young
838,548,Krishna Patel,26,krishna.patel358@yahoo.com,POL039243,Premium,2025,Max Bupa,494950,2024,Young
839,681,Aditya Patel,26,aditya.patel268@gmail.com,POL118796,Gold,2025,Star Health,629782,2023,Young
840,566,Aarav Yadav,26,aarav.yadav345@outlook.com,POL522453,Gold,2025,Star Health,630382,2023,Young
...,...,...,...,...,...,...,...,...,...,...,...
1730,1729,Krishna Reddy,26,krishna.reddy309@yahoo.com,POL036334,Premium,2026,HDFC Ergo,573125,2026,Young
1824,1823,Pranav Patel,26,pranav.patel13@yahoo.com,POL877545,Platinum,2026,ICICI Lombard,760469,2023,Young
1891,1890,Sai Singh,26,sai.singh263@yahoo.com,POL117206,Premium,2026,HDFC Ergo,741864,2023,Young
1949,1948,Pranav Joshi,25,pranav.joshi820@yahoo.com,POL807612,Premium,2026,ICICI Lombard,296760,2024,Young
1988,1987,Aditya Singh,26,aditya.singh106@yahoo.com,POL367519,Platinum,2026,New India Assurance,408275,2024,Young

In [136]:
patient_data['Patient_Age_category'].unique()

array(['Older Age', 'Early Older', 'Middle Age', 'Young'], dtype=object)

In [137]:
patient_data['Provider_Name']=patient_data['Provider_Name'].where(patient_data['Provider_Name']!='New India Assurance',"India Insurance")

In [138]:
patient_data['Provider_Name'].unique()

array(['HDFC Ergo', 'Star Health', 'ICICI Lombard', 'Max Bupa',
       'India Insurance'], dtype=object)

In [139]:
## Mask

#it will chnage the value whenever the condition is True

## now 
I want to map 

age description 

0 to 29 ---> Young
30 to 49 ---> Middle Age
50 to 60 ---> Early Older

>> 60 ----> Older Age

In [140]:
patient_data['Mask_Age_example']= patient_data['Patient_Age'].mask(patient_data['Patient_Age']<30,"Young").mask((patient_data['Patient_Age']>=30)&(patient_data['Patient_Age']<50 ),'Middle Age').mask((patient_data['Patient_Age']>=50)&(patient_data['Patient_Age']<=60 ),"Early Older").mask(patient_data['Patient_Age']>60,'Older Age')

In [141]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example
0,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age
1,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age
2,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age
3,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age
4,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age
...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older
1999,1998,Aarav Sharma,72,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age
2000,1999,Ishaan Joshi,65,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older

In [142]:
bins = [0, 30, 50, 60, 100]
labels = ["Young", "Middle Age", "Early Older", "Senior"]

patient_data["Age_remark"] = pd.cut(patient_data["Patient_Age"] , bins=bins, labels=labels, right=True)

In [143]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark
0,80,Krishna Kumar,80,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior
1,118,Sai Yadav,80,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior
2,75,Sai Joshi,80,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior
3,604,Pranav Patel,80,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior
4,591,Sai Reddy,80,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age,Middle Age
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older,Early Older
1999,1998,Aarav Sharma,72,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age,Senior
2000,1999,Ishaan Joshi,65,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age,Senior
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older,Early Older

isna()
isnull()

to identify the null values in the dataframe

In [144]:
patient_data.isna().sum()

Patient_ID              0
Patient_Name            0
Patient_Age             0
Email                   0
Policy_Number           0
Policy_Type             0
year                    0
Provider_Name           0
Coverage_Amount         0
Start_Year              0
Patient_Age_category    0
Mask_Age_example        0
Age_remark              0
dtype: int64

In [145]:
patient_data.isnull().sum()

Patient_ID              0
Patient_Name            0
Patient_Age             0
Email                   0
Policy_Number           0
Policy_Type             0
year                    0
Provider_Name           0
Coverage_Amount         0
Start_Year              0
Patient_Age_category    0
Mask_Age_example        0
Age_remark              0
dtype: int64

In [146]:
## create null value in age 

patient_data["Patient_Age"]=patient_data["Patient_Age"].mask(patient_data["Patient_Age"]>60,None)

In [147]:
patient_data.isnull().sum()

Patient_ID                0
Patient_Name              0
Patient_Age             646
Email                     0
Policy_Number             0
Policy_Type               0
year                      0
Provider_Name             0
Coverage_Amount           0
Start_Year                0
Patient_Age_category      0
Mask_Age_example          0
Age_remark                0
dtype: int64

In [148]:
patient_data.notnull().sum()

Patient_ID              2000
Patient_Name            2000
Patient_Age             1354
Email                   2000
Policy_Number           2000
Policy_Type             2000
year                    2000
Provider_Name           2000
Coverage_Amount         2000
Start_Year              2000
Patient_Age_category    2000
Mask_Age_example        2000
Age_remark              2000
dtype: int64

In [149]:
patient_data["Patient_Age"]=patient_data["Patient_Age"].fillna(77)

In [150]:
patient_data.isnull().sum()

Patient_ID              0
Patient_Name            0
Patient_Age             0
Email                   0
Policy_Number           0
Policy_Type             0
year                    0
Provider_Name           0
Coverage_Amount         0
Start_Year              0
Patient_Age_category    0
Mask_Age_example        0
Age_remark              0
dtype: int64

## Apply()
Apply function used in the pandas dataframe or series to apply custom function on the row, columns , individual data .

when pandas in-build function is not enough and you want to apply custom function over column, row etc in such case we use Apply

In [151]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark
0,80,Krishna Kumar,77.0,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior
1,118,Sai Yadav,77.0,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior
2,75,Sai Joshi,77.0,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior
3,604,Pranav Patel,77.0,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior
4,591,Sai Reddy,77.0,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31.0,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age,Middle Age
1998,1997,Ishaan Yadav,59.0,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older,Early Older
1999,1998,Aarav Sharma,77.0,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age,Senior
2000,1999,Ishaan Joshi,77.0,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age,Senior
2001,2000,Vivaan Singh,57.0,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older,Early Older

In [152]:
patient_data['Email_domain']=patient_data['Email'].apply(lambda x : x.split('@')[1])

In [153]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain
0,80,Krishna Kumar,77.0,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior,yahoo.com
1,118,Sai Yadav,77.0,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior,gmail.com
2,75,Sai Joshi,77.0,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior,outlook.com
3,604,Pranav Patel,77.0,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior,yahoo.com
4,591,Sai Reddy,77.0,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior,yahoo.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31.0,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age,Middle Age,outlook.com
1998,1997,Ishaan Yadav,59.0,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older,Early Older,outlook.com
1999,1998,Aarav Sharma,77.0,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age,Senior,yahoo.com
2000,1999,Ishaan Joshi,77.0,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age,Senior,outlook.com
2001,2000,Vivaan Singh,57.0,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older,Early Older,yahoo.com

risk_factor 

if age>50 and Policy type == "Basic"  ==> High risk
if age>50 and Policy type =="Gold" ==>  Normal risk
if age>50 and Policy type == "Platinum" ==> Normal

In [154]:
def risk_factor(row):
    if row["Patient_Age"] >= 50 and row["Policy_Type"] == "Basic":
        return "High Risk"
    elif row['Patient_Age']>=50 and row["Policy_Type"]=="Gold":
        return "Normal Risk"
    elif row['Patient_Age']>=50 and row['Policy_Type'] =='Platinum':
        return "Normal"
    else:
        return "Age is below 50"

In [155]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain
0,80,Krishna Kumar,77.0,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior,yahoo.com
1,118,Sai Yadav,77.0,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior,gmail.com
2,75,Sai Joshi,77.0,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior,outlook.com
3,604,Pranav Patel,77.0,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior,yahoo.com
4,591,Sai Reddy,77.0,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior,yahoo.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31.0,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age,Middle Age,outlook.com
1998,1997,Ishaan Yadav,59.0,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older,Early Older,outlook.com
1999,1998,Aarav Sharma,77.0,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age,Senior,yahoo.com
2000,1999,Ishaan Joshi,77.0,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age,Senior,outlook.com
2001,2000,Vivaan Singh,57.0,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older,Early Older,yahoo.com

In [156]:
patient_data['Patient_Age']=patient_data['Patient_Age'].astype(int)

In [157]:
patient_data.columns

Index(['Patient_ID', 'Patient_Name', 'Patient_Age', 'Email', 'Policy_Number',
       'Policy_Type', 'year', 'Provider_Name', 'Coverage_Amount', 'Start_Year',
       'Patient_Age_category', 'Mask_Age_example', 'Age_remark',
       'Email_domain'],
      dtype='object')

In [158]:
patient_data['risk_factor'] = patient_data.apply(risk_factor,axis=1)

In [159]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor
0,80,Krishna Kumar,77,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior,yahoo.com,Normal
1,118,Sai Yadav,77,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior,gmail.com,Normal
2,75,Sai Joshi,77,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior,outlook.com,Age is below 50
3,604,Pranav Patel,77,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50
4,591,Sai Reddy,77,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older,Early Older,outlook.com,High Risk
1999,1998,Aarav Sharma,77,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age,Senior,yahoo.com,Normal
2000,1999,Ishaan Joshi,77,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age,Senior,outlook.com,Age is below 50
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older,Early Older,yahoo.com,Normal

## Map() 

Map in pandas used to map or transform value in a single column, 

Map does not work on the whole data frame , it works on the only sigle columns

In [160]:
policy_map={
    "Basic":'B',
    "Platinum":'Plt',
    "Gold" : 'G',
    'Premium' : 'Pre'}

In [161]:
patient_data['policy_map']=patient_data['Policy_Type'].map(policy_map)

In [162]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor,policy_map
0,80,Krishna Kumar,77,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior,yahoo.com,Normal,Plt
1,118,Sai Yadav,77,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior,gmail.com,Normal,Plt
2,75,Sai Joshi,77,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre
3,604,Pranav Patel,77,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre
4,591,Sai Reddy,77,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50,Pre
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older,Early Older,outlook.com,High Risk,B
1999,1998,Aarav Sharma,77,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age,Senior,yahoo.com,Normal,Plt
2000,1999,Ishaan Joshi,77,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older,Early Older,yahoo.com,Normal,Plt

In [163]:
## columns split

patient_data[['First_name','Last_name']] = patient_data['Patient_Name'].str.split(" ",expand=True)

In [164]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor,policy_map,First_name,Last_name
0,80,Krishna Kumar,77,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior,yahoo.com,Normal,Plt,Krishna,Kumar
1,118,Sai Yadav,77,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior,gmail.com,Normal,Plt,Sai,Yadav
2,75,Sai Joshi,77,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Sai,Joshi
3,604,Pranav Patel,77,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre,Pranav,Patel
4,591,Sai Reddy,77,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre,Sai,Reddy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50,Pre,Aarav,Mehta
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older,Early Older,outlook.com,High Risk,B,Ishaan,Yadav
1999,1998,Aarav Sharma,77,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age,Senior,yahoo.com,Normal,Plt,Aarav,Sharma
2000,1999,Ishaan Joshi,77,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Ishaan,Joshi
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older,Early Older,yahoo.com,Normal,Plt,Vivaan,Singh

strip , lower , upper,Title

In [165]:
## strip is used to remove leading and trailing space from the string
patient_data['Patient_Name'].str.strip().str.lower()

0       krishna kumar
1           sai yadav
2           sai joshi
3        pranav patel
4           sai reddy
            ...
1997      aarav mehta
1998     ishaan yadav
1999     aarav sharma
2000     ishaan joshi
2001     vivaan singh
Name: Patient_Name, Length: 2000, dtype: object

In [166]:
patient_data['Patient_Name'].str.lower()

0       krishna kumar
1           sai yadav
2           sai joshi
3        pranav patel
4           sai reddy
            ...
1997      aarav mehta
1998     ishaan yadav
1999     aarav sharma
2000     ishaan joshi
2001     vivaan singh
Name: Patient_Name, Length: 2000, dtype: object

In [167]:
patient_data['Patient_Name'].str.upper()

0       KRISHNA KUMAR
1           SAI YADAV
2           SAI JOSHI
3        PRANAV PATEL
4           SAI REDDY
            ...
1997      AARAV MEHTA
1998     ISHAAN YADAV
1999     AARAV SHARMA
2000     ISHAAN JOSHI
2001     VIVAAN SINGH
Name: Patient_Name, Length: 2000, dtype: object

In [168]:
patient_data['Patient_Name'].str.title()

0       Krishna Kumar
1           Sai Yadav
2           Sai Joshi
3        Pranav Patel
4           Sai Reddy
            ...
1997      Aarav Mehta
1998     Ishaan Yadav
1999     Aarav Sharma
2000     Ishaan Joshi
2001     Vivaan Singh
Name: Patient_Name, Length: 2000, dtype: object

Group by
Multiple columns group by
agg function
pivot()
Pivot_tables

In [169]:
## How many member each provider has 

patient_data.groupby(['Provider_Name'])['Patient_ID'].count()

Provider_Name
HDFC Ergo          378
ICICI Lombard      400
India Insurance    421
Max Bupa           396
Star Health        405
Name: Patient_ID, dtype: int64

In [170]:
## how many patient has insurence more than one provider

patient_data.groupby(['Patient_Name'])['Provider_Name'].count()

Patient_Name
Aarav Gupta      14
Aarav Joshi      25
Aarav Kumar      22
Aarav Mehta      22
Aarav Patel      16
                 ..
Vivaan Reddy     22
Vivaan Sharma    21
Vivaan Singh     23
Vivaan Verma     24
Vivaan Yadav     16
Name: Provider_Name, Length: 100, dtype: int64

In [171]:
## average coverage amount by each provider

result=patient_data.groupby(['Provider_Name'])['Coverage_Amount'].mean().reset_index()

In [172]:
result.to_csv('result.csv',index=False)

In [173]:
patient_data.head()

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor,policy_map,First_name,Last_name
0,80,Krishna Kumar,77,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior,yahoo.com,Normal,Plt,Krishna,Kumar
1,118,Sai Yadav,77,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior,gmail.com,Normal,Plt,Sai,Yadav
2,75,Sai Joshi,77,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Sai,Joshi
3,604,Pranav Patel,77,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre,Pranav,Patel
4,591,Sai Reddy,77,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre,Sai,Reddy

In [174]:
## how much coverage amount each provider is given in each category of age

patient_data.groupby(['Age_remark','Provider_Name'])['Coverage_Amount'].sum().reset_index()

C:\Users\prash\AppData\Local\Temp\ipykernel_23316\1707806099.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  patient_data.groupby(['Age_remark','Provider_Name'])['Coverage_Amount'].sum().reset_index()

     Age_remark    Provider_Name  Coverage_Amount
0         Young        HDFC Ergo         40895924
1         Young    ICICI Lombard         31574824
2         Young  India Insurance         53266954
3         Young         Max Bupa         49059856
4         Young      Star Health         53443043
5    Middle Age        HDFC Ergo         70366073
6    Middle Age    ICICI Lombard         64124543
7    Middle Age  India Insurance         65881681
8    Middle Age         Max Bupa         71966464
9    Middle Age      Star Health         81454103
10  Early Older        HDFC Ergo         32404856
11  Early Older    ICICI Lombard         34184216
12  Early Older  India Insurance         33062756
13  Early Older         Max Bupa         31081022
14  Early Older      Star Health         29593116
15       Senior        HDFC Ergo         62175121
16       Senior    ICICI Lombard         77606329
17       Senior  India Insurance         72011313
18       Senior         Max Bupa         66905713
19       Senior      Star Health         66482748

In [175]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor,policy_map,First_name,Last_name
0,80,Krishna Kumar,77,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior,yahoo.com,Normal,Plt,Krishna,Kumar
1,118,Sai Yadav,77,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior,gmail.com,Normal,Plt,Sai,Yadav
2,75,Sai Joshi,77,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Sai,Joshi
3,604,Pranav Patel,77,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre,Pranav,Patel
4,591,Sai Reddy,77,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre,Sai,Reddy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50,Pre,Aarav,Mehta
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older,Early Older,outlook.com,High Risk,B,Ishaan,Yadav
1999,1998,Aarav Sharma,77,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age,Senior,yahoo.com,Normal,Plt,Aarav,Sharma
2000,1999,Ishaan Joshi,77,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Ishaan,Joshi
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older,Early Older,yahoo.com,Normal,Plt,Vivaan,Singh

In [176]:
## i want to find out each provider count , name against Patient_name
pd.set_option("display.max_colwidth", None)

patient_data.groupby(['Patient_Name']).agg(
    provider_count=('Provider_Name','nunique'),
    provider_list=('Provider_Name',lambda x : list(x.unique()))
)

,provider_count,provider_list
Patient_Name,,
Aarav Gupta,5,"[ICICI Lombard, India Insurance, HDFC Ergo, Max Bupa, Star Health]"
Aarav Joshi,5,"[ICICI Lombard, HDFC Ergo, India Insurance, Star Health, Max Bupa]"
Aarav Kumar,5,"[Star Health, ICICI Lombard, HDFC Ergo, Max Bupa, India Insurance]"
Aarav Mehta,5,"[Max Bupa, India Insurance, Star Health, HDFC Ergo, ICICI Lombard]"
Aarav Patel,5,"[Max Bupa, HDFC Ergo, Star Health, ICICI Lombard, India Insurance]"
...,...,...
Vivaan Reddy,4,"[HDFC Ergo, Max Bupa, Star Health, India Insurance]"
Vivaan Sharma,5,"[ICICI Lombard, Max Bupa, India Insurance, Star Health, HDFC Ergo]"
Vivaan Singh,5,"[India Insurance, Max Bupa, ICICI Lombard, HDFC Ergo, Star Health]"
Vivaan Verma,5,"[ICICI Lombard, India Insurance, HDFC Ergo, Star Health, Max Bupa]"
Vivaan Yadav,5,"[Max Bupa, HDFC Ergo, Star Health, ICICI Lombard, India Insurance]"

In [177]:
## find the sum , min ,max, mean of coverage amount

patient_data['Coverage_Amount'].agg(['sum','max','min','mean'])

sum     1.087541e+09
max     9.996760e+05
min     1.008620e+05
mean    5.437703e+05
Name: Coverage_Amount, dtype: float64

In [178]:
patient_data.groupby(['Provider_Name']).agg(
    
    total_coverage=('Coverage_Amount',"sum"),
    Avg_coverage=('Coverage_Amount',"mean"),
    Max_coverage=('Coverage_Amount',"max"),
    min_coverage=('Coverage_Amount','min')
    
    
    
)

                 total_coverage   Avg_coverage  Max_coverage  min_coverage
Provider_Name
HDFC Ergo             205841974  544555.486772        997547        102853
ICICI Lombard         207489912  518724.780000        995568        100862
India Insurance       224222704  532595.496437        999111        103691
Max Bupa              219013055  553063.270202        997544        103883
Star Health           230973010  570303.728395        999676        103211

## Pivot and Pivot tables

Both pivot and pivot tables convert the data , reshape the data (row converts into columns)

`syntax of pivot `

df.pivot(index, columns , values)


- pivot() is used to reshape data but it cannot handle duplicate values.
- pivot_table() is more powerful because it supports aggregation functions like sum, mean, count, etc.

In [179]:
patient_data.pivot(columns='Provider_Name',values='Coverage_Amount')

Provider_Name,HDFC Ergo,ICICI Lombard,India Insurance,Max Bupa,Star Health
0,851420.0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,829205.0
2,NaN,NaN,NaN,NaN,659481.0
3,135569.0,NaN,NaN,NaN,NaN
4,954316.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...
1997,NaN,NaN,NaN,NaN,484092.0
1998,NaN,NaN,NaN,NaN,579515.0
1999,NaN,NaN,NaN,644437.0,NaN
2000,NaN,NaN,NaN,965221.0,NaN
2001,NaN,213392.0,NaN,NaN,NaN

In [180]:
## pivot_table

## Want to analyze the coverage amount by provider name and policy type

patient_data.pivot_table(index='Provider_Name',columns='Policy_Type',values='Coverage_Amount',aggfunc=['sum','mean'])

                      sum                                         mean  \
Policy_Type         Basic      Gold  Platinum   Premium          Basic
Provider_Name
HDFC Ergo        46728285  47873876  58342716  52897097  507916.141304
ICICI Lombard    44534618  56220861  61306940  45427493  517844.395349
India Insurance  58156330  63626761  52910224  49529389  528693.909091
Max Bupa         53088825  52601759  52713565  60608906  558829.736842
Star Health      60751334  53364804  56668074  60188798  607513.340000


Policy_Type               Gold       Platinum        Premium
Provider_Name
HDFC Ergo        526086.549451  571987.411765  568785.989247
ICICI Lombard    535436.771429  542539.292035  473203.052083
India Insurance  563068.681416  539900.244898  495293.890000
Max Bupa         531330.898990  554879.631579  566438.373832
Star Health      550152.618557  566680.740000  557303.685185

In [181]:
patient_data.pivot_table(index='Provider_Name',columns='Policy_Type',values=["Coverage_Amount","Patient_Name"],aggfunc={"Coverage_Amount":["sum","mean"],
                                                                                                             "Patient_Name":"nunique"})

                Coverage_Amount                                               \
                           mean
Policy_Type               Basic           Gold       Platinum        Premium
Provider_Name
HDFC Ergo         507916.141304  526086.549451  571987.411765  568785.989247
ICICI Lombard     517844.395349  535436.771429  542539.292035  473203.052083
India Insurance   528693.909091  563068.681416  539900.244898  495293.890000
Max Bupa          558829.736842  531330.898990  554879.631579  566438.373832
Star Health       607513.340000  550152.618557  566680.740000  557303.685185

                                                        Patient_Name       \
                      sum                                    nunique
Policy_Type         Basic      Gold  Platinum   Premium        Basic Gold
Provider_Name
HDFC Ergo        46728285  47873876  58342716  52897097           59   61
ICICI Lombard    44534618  56220861  61306940  45427493           56   69
India Insurance  58156330  63626761  52910224  49529389           62   68
Max Bupa         53088825  52601759  52713565  60608906           59   65
Star Health      60751334  53364804  56668074  60188798           63   64



Policy_Type     Platinum Premium
Provider_Name
HDFC Ergo             61      63
ICICI Lombard         67      65
India Insurance       59      68
Max Bupa              63      62
Star Health           59      72

## Stack

convert the dataframe wider to longer.

Stack : stacking is process of transformation of multiple columns into single columns.

In [182]:
stack_data=patient_data.stack()

In [183]:
stack_data[0:150]

0  Patient_ID                               80
   Patient_Name                  Krishna Kumar
   Patient_Age                              77
   Email            krishna.kumar274@yahoo.com
   Policy_Number                     POL078226
                               ...
8  Patient_Name                   Ishaan Verma
   Patient_Age                              77
   Email             ishaan.verma174@yahoo.com
   Policy_Number                     POL142431
   Policy_Type                         Premium
Length: 150, dtype: object

In [184]:
stack_data.to_csv("stack.csv")

In [185]:
stack_data.unstack()

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor,policy_map,First_name,Last_name
0,80,Krishna Kumar,77,krishna.kumar274@yahoo.com,POL078226,Platinum,2025,HDFC Ergo,851420,2026,Older Age,Older Age,Senior,yahoo.com,Normal,Plt,Krishna,Kumar
1,118,Sai Yadav,77,sai.yadav586@gmail.com,POL034543,Platinum,2025,Star Health,829205,2023,Older Age,Older Age,Senior,gmail.com,Normal,Plt,Sai,Yadav
2,75,Sai Joshi,77,sai.joshi804@outlook.com,POL875971,Premium,2025,Star Health,659481,2025,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Sai,Joshi
3,604,Pranav Patel,77,pranav.patel329@yahoo.com,POL097005,Premium,2025,HDFC Ergo,135569,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre,Pranav,Patel
4,591,Sai Reddy,77,sai.reddy717@yahoo.com,POL640591,Premium,2025,HDFC Ergo,954316,2026,Older Age,Older Age,Senior,yahoo.com,Age is below 50,Pre,Sai,Reddy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,1996,Aarav Mehta,31,aarav.mehta63@outlook.com,POL748260,Premium,2026,Star Health,484092,2024,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50,Pre,Aarav,Mehta
1998,1997,Ishaan Yadav,59,ishaan.yadav830@outlook.com,POL725846,Basic,2026,Star Health,579515,2023,Early Older,Early Older,Early Older,outlook.com,High Risk,B,Ishaan,Yadav
1999,1998,Aarav Sharma,77,aarav.sharma12@yahoo.com,POL362369,Platinum,2026,Max Bupa,644437,2023,Older Age,Older Age,Senior,yahoo.com,Normal,Plt,Aarav,Sharma
2000,1999,Ishaan Joshi,77,ishaan.joshi92@outlook.com,POL921223,Premium,2026,Max Bupa,965221,2024,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Ishaan,Joshi
2001,2000,Vivaan Singh,57,vivaan.singh214@yahoo.com,POL309917,Platinum,2026,ICICI Lombard,213392,2024,Early Older,Early Older,Early Older,yahoo.com,Normal,Plt,Vivaan,Singh

In [186]:
df1= patient_data.set_index(['Patient_Name','Patient_Age'])

In [187]:
df2=df1.stack()

In [188]:
df2[0:20]

Patient_Name   Patient_Age
Krishna Kumar  77           Patient_ID                                      80
                            Email                   krishna.kumar274@yahoo.com
                            Policy_Number                            POL078226
                            Policy_Type                               Platinum
                            year                                          2025
                            Provider_Name                            HDFC Ergo
                            Coverage_Amount                             851420
                            Start_Year                                    2026
                            Patient_Age_category                     Older Age
                            Mask_Age_example                         Older Age
                            Age_remark                                  Senior
                            Email_domain                             yahoo.com
                            risk_factor                                 Normal
                            policy_map                                     Plt
                            First_name                                 Krishna
                            Last_name                                    Kumar
Sai Yadav      77           Patient_ID                                     118
                            Email                       sai.yadav586@gmail.com
                            Policy_Number                            POL034543
                            Policy_Type                               Platinum
dtype: object

In [189]:
df2.unstack()

ValueError: Index contains duplicate entries, cannot reshape

In [190]:
pd.set_option("display.max_rows", 200)

df2.xs("Aditya Yadav")

Patient_Age
77           Patient_ID                             705
             Email            aditya.yadav977@gmail.com
             Policy_Number                    POL543738
             Policy_Type                       Platinum
             year                                  2025
                                        ...
18           Email_domain                     gmail.com
             risk_factor                Age is below 50
             policy_map                               G
             First_name                          Aditya
             Last_name                            Yadav
Length: 336, dtype: object

In [191]:
patient_data[patient_data["Patient_Name"]=="Aditya Yadav"]

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor,policy_map,First_name,Last_name
11,705,Aditya Yadav,77,aditya.yadav977@gmail.com,POL543738,Platinum,2025,India Insurance,862709,2024,Older Age,Older Age,Senior,gmail.com,Normal,Plt,Aditya,Yadav
223,714,Aditya Yadav,77,aditya.yadav734@outlook.com,POL362343,Basic,2025,Max Bupa,392441,2024,Older Age,Older Age,Senior,outlook.com,High Risk,B,Aditya,Yadav
224,207,Aditya Yadav,77,aditya.yadav433@gmail.com,POL098699,Premium,2025,Max Bupa,815200,2023,Older Age,Older Age,Senior,gmail.com,Age is below 50,Pre,Aditya,Yadav
359,270,Aditya Yadav,57,aditya.yadav815@yahoo.com,POL981449,Gold,2025,HDFC Ergo,500601,2026,Early Older,Early Older,Early Older,yahoo.com,Normal Risk,G,Aditya,Yadav
412,8,Aditya Yadav,53,aditya.yadav682@outlook.com,POL341551,Platinum,2025,ICICI Lombard,603637,2024,Early Older,Early Older,Early Older,outlook.com,Normal,Plt,Aditya,Yadav
507,440,Aditya Yadav,48,aditya.yadav516@outlook.com,POL934341,Premium,2025,Max Bupa,585245,2024,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50,Pre,Aditya,Yadav
520,437,Aditya Yadav,47,aditya.yadav831@outlook.com,POL096952,Gold,2025,Max Bupa,291597,2024,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50,G,Aditya,Yadav
630,44,Aditya Yadav,39,aditya.yadav389@yahoo.com,POL506246,Basic,2025,Star Health,262906,2026,Middle Age,Middle Age,Middle Age,yahoo.com,Age is below 50,B,Aditya,Yadav
1042,1043,Aditya Yadav,49,aditya.yadav917@gmail.com,POL527669,Basic,2026,Max Bupa,871732,2026,Middle Age,Middle Age,Middle Age,gmail.com,Age is below 50,B,Aditya,Yadav
1051,1052,Aditya Yadav,54,aditya.yadav448@outlook.com,POL854244,Basic,2026,HDFC Ergo,430321,2025,Early Older,Early Older,Early Older,outlook.com,High Risk,B,Aditya,Yadav
1117,1118,Aditya Yadav,77,aditya.yadav981@outlook.com,POL228305,Gold,2026,HDFC Ergo,181651,2024,Older Age,Older Age,Senior,outlook.com,Normal Risk,G,Aditya,Yadav
1137,1138,Aditya Yadav,58,aditya.yadav749@gmail.com,POL353821,Basic,2026,Max Bupa,281167,2024,Early Older,Early Older,Early Older,gmail.com,High Risk,B,Aditya,Yadav
1195,1195,Aditya Yadav,59,aditya.yadav211@outlook.com,POL617696,Premium,2026,India Insurance,576007,2025,Early Older,Early Older,Early Older,outlook.com,Age is below 50,Pre,Aditya,Yadav
1262,1262,Aditya Yadav,77,aditya.yadav909@outlook.com,POL077105,Premium,2026,Max Bupa,208021,2023,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Aditya,Yadav
1307,1307,Aditya Yadav,77,aditya.yadav90@outlook.com,POL301529,Basic,2026,ICICI Lombard,473882,2026,Older Age,Older Age,Senior,outlook.com,High Risk,B,Aditya,Yadav
1365,1365,Aditya Yadav,77,aditya.yadav861@gmail.com,POL853897,Platinum,2026,ICICI Lombard,801135,2026,Older Age,Older Age,Senior,gmail.com,Normal,Plt,Aditya,Yadav
1411,1411,Aditya Yadav,77,aditya.yadav565@outlook.com,POL300108,Platinum,2026,ICICI Lombard,990632,2024,Older Age,Older Age,Senior,outlook.com,Normal,Plt,Aditya,Yadav
1553,1553,Aditya Yadav,52,aditya.yadav54@gmail.com,POL116513,Platinum,2026,Star Health,724201,2026,Early Older,Early Older,Early Older,gmail.com,Normal,Plt,Aditya,Yadav
1652,1651,Aditya Yadav,77,aditya.yadav59@yahoo.com,POL717166,Platinum,2026,Star Health,142342,2024,Older Age,Older Age,Senior,yahoo.com,Normal,Plt,Aditya,Yadav
1704,1703,Aditya Yadav,77,aditya.yadav85@yahoo.com,POL128407,Basic,2026,HDFC Ergo,163559,2023,Older Age,Older Age,Senior,yahoo.com,High Risk,B,Aditya,Yadav
1913,1912,Aditya Yadav,18,aditya.yadav792@gmail.com,POL833149,Gold,2026,Star Health,699542,2023,Young,Young,Young,gmail.com,Age is below 50,G,Aditya,Yadav

## Cross Tab
crosstab created frequency table between two or more columns

In [192]:
pd.crosstab(patient_data["Provider_Name"],patient_data['Policy_Type'])

Policy_Type      Basic  Gold  Platinum  Premium
Provider_Name
HDFC Ergo           92    91       102       93
ICICI Lombard       86   105       113       96
India Insurance    110   113        98      100
Max Bupa            95    99        95      107
Star Health        100    97       100      108

In [193]:
patient_data.pivot_table(index='Provider_Name',columns='Policy_Type',values='Patient_Age',aggfunc='count')

Policy_Type      Basic  Gold  Platinum  Premium
Provider_Name
HDFC Ergo           92    91       102       93
ICICI Lombard       86   105       113       96
India Insurance    110   113        98      100
Max Bupa            95    99        95      107
Star Health        100    97       100      108

In [194]:
pd.crosstab(patient_data['Patient_Age_category'],patient_data['Policy_Type'])

Policy_Type           Basic  Gold  Platinum  Premium
Patient_Age_category
Early Older              80    70        72       67
Middle Age              149   170       158      166
Older Age               175   160       171      175
Young                    79   105       107       96

## Rank 

The Rank method assign the rank to values in dataframe and series.
By default rank is in ascending order

In [195]:
result=patient_data.groupby('Policy_Type')['Coverage_Amount'].sum().reset_index()

In [196]:
result['rank']=result['Coverage_Amount'].rank(ascending=False, method='dense')

In [197]:
result

  Policy_Type  Coverage_Amount  rank
0       Basic        263259392   4.0
1        Gold        273688061   2.0
2    Platinum        281941519   1.0
3     Premium        268651683   3.0

In [198]:
## find out top 1 policy type in each year

result=patient_data.groupby(['Start_Year','Policy_Type'])['Coverage_Amount'].sum().reset_index()

In [199]:
result['rank']=result.groupby('Start_Year')['Coverage_Amount'].rank(method='dense')

In [200]:
result[result['rank']==1.0]

    Start_Year Policy_Type  Coverage_Amount  rank
1         2023        Gold         62449381   1.0
7         2024     Premium         60833575   1.0
8         2025       Basic         67276949   1.0
15        2026     Premium         62277460   1.0

Rolling window()
Rolling window in Pandas is used when you want to perform calculation on fixed-size moving window of rows

it is used in 

- Time series
- Moving Average
- Trend Analysis
- smoothing data

rolling window apply calculation on the moving group or rows instant of the entire datasets

In [201]:
patient_data['Coverage_Amount'].rolling(3).mean()

0                 NaN
1                 NaN
2       780035.333333
3       541418.333333
4       583122.000000
            ...
1997    695307.000000
1998    623971.333333
1999    569348.000000
2000    729724.333333
2001    607683.333333
Name: Coverage_Amount, Length: 2000, dtype: float64

In [202]:
patient_data['Coverage_Amount']

0       851420
1       829205
2       659481
3       135569
4       954316
         ...
1997    484092
1998    579515
1999    644437
2000    965221
2001    213392
Name: Coverage_Amount, Length: 2000, dtype: int64

In [203]:
# Rolling Average Coverage Amount per Policy Type (over years)

patient_data.sort_values(["Policy_Type", "Start_Year"],inplace=True)

In [204]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor,policy_map,First_name,Last_name
17,340,Ishaan Kumar,77,ishaan.kumar451@outlook.com,POL875129,Basic,2025,India Insurance,233949,2023,Older Age,Older Age,Senior,outlook.com,High Risk,B,Ishaan,Kumar
30,384,Aarav Singh,77,aarav.singh557@yahoo.com,POL052224,Basic,2025,Max Bupa,661113,2023,Older Age,Older Age,Senior,yahoo.com,High Risk,B,Aarav,Singh
40,880,Reyansh Mehta,77,reyansh.mehta554@outlook.com,POL468441,Basic,2025,ICICI Lombard,223344,2023,Older Age,Older Age,Senior,outlook.com,High Risk,B,Reyansh,Mehta
52,912,Sai Kumar,77,sai.kumar119@outlook.com,POL544288,Basic,2025,ICICI Lombard,513156,2023,Older Age,Older Age,Senior,outlook.com,High Risk,B,Sai,Kumar
87,213,Arjun Reddy,77,arjun.reddy424@gmail.com,POL101484,Basic,2025,Max Bupa,665410,2023,Older Age,Older Age,Senior,gmail.com,High Risk,B,Arjun,Reddy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1954,1953,Aditya Joshi,31,aditya.joshi357@outlook.com,POL859688,Premium,2026,India Insurance,821254,2026,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50,Pre,Aditya,Joshi
1967,1966,Vihaan Mehta,77,vihaan.mehta781@outlook.com,POL545586,Premium,2026,ICICI Lombard,661434,2026,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Vihaan,Mehta
1968,1967,Reyansh Joshi,33,reyansh.joshi279@yahoo.com,POL690400,Premium,2026,HDFC Ergo,460896,2026,Middle Age,Middle Age,Middle Age,yahoo.com,Age is below 50,Pre,Reyansh,Joshi
1982,1981,Sai Verma,77,sai.verma933@gmail.com,POL355570,Premium,2026,Star Health,325225,2026,Older Age,Older Age,Senior,gmail.com,Age is below 50,Pre,Sai,Verma
1991,1990,Krishna Yadav,49,krishna.yadav340@yahoo.com,POL193513,Premium,2026,Star Health,327837,2026,Middle Age,Middle Age,Middle Age,yahoo.com,Age is below 50,Pre,Krishna,Yadav

In [205]:
patient_data['rolling_avg']=(patient_data.groupby(['Policy_Type','Start_Year'])['Coverage_Amount'].transform(lambda x : x.rolling(window=3,min_periods=1).mean())
                             
                             )

In [206]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor,policy_map,First_name,Last_name,rolling_avg
17,340,Ishaan Kumar,77,ishaan.kumar451@outlook.com,POL875129,Basic,2025,India Insurance,233949,2023,Older Age,Older Age,Senior,outlook.com,High Risk,B,Ishaan,Kumar,233949.000000
30,384,Aarav Singh,77,aarav.singh557@yahoo.com,POL052224,Basic,2025,Max Bupa,661113,2023,Older Age,Older Age,Senior,yahoo.com,High Risk,B,Aarav,Singh,447531.000000
40,880,Reyansh Mehta,77,reyansh.mehta554@outlook.com,POL468441,Basic,2025,ICICI Lombard,223344,2023,Older Age,Older Age,Senior,outlook.com,High Risk,B,Reyansh,Mehta,372802.000000
52,912,Sai Kumar,77,sai.kumar119@outlook.com,POL544288,Basic,2025,ICICI Lombard,513156,2023,Older Age,Older Age,Senior,outlook.com,High Risk,B,Sai,Kumar,465871.000000
87,213,Arjun Reddy,77,arjun.reddy424@gmail.com,POL101484,Basic,2025,Max Bupa,665410,2023,Older Age,Older Age,Senior,gmail.com,High Risk,B,Arjun,Reddy,467303.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1954,1953,Aditya Joshi,31,aditya.joshi357@outlook.com,POL859688,Premium,2026,India Insurance,821254,2026,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50,Pre,Aditya,Joshi,692585.666667
1967,1966,Vihaan Mehta,77,vihaan.mehta781@outlook.com,POL545586,Premium,2026,ICICI Lombard,661434,2026,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Vihaan,Mehta,817166.666667
1968,1967,Reyansh Joshi,33,reyansh.joshi279@yahoo.com,POL690400,Premium,2026,HDFC Ergo,460896,2026,Middle Age,Middle Age,Middle Age,yahoo.com,Age is below 50,Pre,Reyansh,Joshi,647861.333333
1982,1981,Sai Verma,77,sai.verma933@gmail.com,POL355570,Premium,2026,Star Health,325225,2026,Older Age,Older Age,Senior,gmail.com,Age is below 50,Pre,Sai,Verma,482518.333333
1991,1990,Krishna Yadav,49,krishna.yadav340@yahoo.com,POL193513,Premium,2026,Star Health,327837,2026,Middle Age,Middle Age,Middle Age,yahoo.com,Age is below 50,Pre,Krishna,Yadav,371319.333333

## Resampling in the pandas

resampling mostly used with datetime data when you have data in one frequency and you want to convery that into another time frequency

In [207]:
import pandas as pd
import numpy as np

# create date range
dates = pd.date_range(start="2024-01-01", periods=800, freq="D")

# create dataframe
df = pd.DataFrame({
    "Date": dates,
    "Sales": np.random.randint(100,500,800)
})

df.set_index("Date", inplace=True)

In [208]:
df

            Sales
Date
2024-01-01    499
2024-01-02    470
2024-01-03    462
2024-01-04    145
2024-01-05    144
...           ...
2026-03-06    487
2026-03-07    445
2026-03-08    229
2026-03-09    444
2026-03-10    229

[800 rows x 1 columns]

In [209]:
## week wise sales
df.resample("W").sum()

            Sales
Date
2024-01-07   2450
2024-01-14   1953
2024-01-21   2402
2024-01-28   2267
2024-02-04   1810
2024-02-11   2173
2024-02-18   2623
2024-02-25   2493
2024-03-03   1116
2024-03-10   2330
2024-03-17   1796
2024-03-24   1240
2024-03-31   2381
2024-04-07   1929
2024-04-14   2610
2024-04-21   1859
2024-04-28   2182
2024-05-05   2560
2024-05-12   2061
2024-05-19   2209
2024-05-26   2036
2024-06-02   1941
2024-06-09   2715
2024-06-16   1606
2024-06-23   2158
2024-06-30   1984
2024-07-07   2274
2024-07-14   1737
2024-07-21   1919
2024-07-28   2241
2024-08-04   2062
2024-08-11   1942
2024-08-18   2051
2024-08-25   2270
2024-09-01   2165
2024-09-08   1737
2024-09-15   2613
2024-09-22   2012
2024-09-29   1897
2024-10-06   2418
2024-10-13   1567
2024-10-20   2465
2024-10-27   2135
2024-11-03   2415
2024-11-10   2119
2024-11-17   2031
2024-11-24   2257
2024-12-01   2432
2024-12-08   2222
2024-12-15   1992
2024-12-22   1890
2024-12-29   2092
2025-01-05   2285
2025-01-12   2582
2025-01-19   2727
2025-01-26   2350
2025-02-02   1822
2025-02-09   2431
2025-02-16   2909
2025-02-23   2272
2025-03-02   2266
2025-03-09   1829
2025-03-16   2174
2025-03-23   2195
2025-03-30   1821
2025-04-06   2287
2025-04-13   2818
2025-04-20   2008
2025-04-27   1463
2025-05-04   1912
2025-05-11   2150
2025-05-18   2323
2025-05-25   2479
2025-06-01   2378
2025-06-08   2649
2025-06-15   1491
2025-06-22   2206
2025-06-29   2229
2025-07-06   2236
2025-07-13   2672
2025-07-20   2138
2025-07-27   1965
2025-08-03   2251
2025-08-10   2547
2025-08-17   1677
2025-08-24   2348
2025-08-31   2276
2025-09-07   2566
2025-09-14   2426
2025-09-21   1686
2025-09-28   1812
2025-10-05   2095
2025-10-12   1679
2025-10-19   1841
2025-10-26   2295
2025-11-02   1861
2025-11-09   2094
2025-11-16   2501
2025-11-23   1912
2025-11-30   2038
2025-12-07   2418
2025-12-14   1824
2025-12-21   2255
2025-12-28   1987
2026-01-04   2133
2026-01-11   2195
2026-01-18   1771
2026-01-25   2159
2026-02-01   2239
2026-02-08   2282
2026-02-15   2008
2026-02-22   2411
2026-03-01   1884
2026-03-08   2094
2026-03-15    673

In [211]:
df.resample("W").agg(["sum","mean","max"])

           Sales
             sum        mean  max
Date
2024-01-07  2450  350.000000  499
2024-01-14  1953  279.000000  490
2024-01-21  2402  343.142857  496
2024-01-28  2267  323.857143  473
2024-02-04  1810  258.571429  447
2024-02-11  2173  310.428571  465
2024-02-18  2623  374.714286  480
2024-02-25  2493  356.142857  491
2024-03-03  1116  159.428571  267
2024-03-10  2330  332.857143  397
2024-03-17  1796  256.571429  495
2024-03-24  1240  177.142857  271
2024-03-31  2381  340.142857  471
2024-04-07  1929  275.571429  456
2024-04-14  2610  372.857143  484
2024-04-21  1859  265.571429  451
2024-04-28  2182  311.714286  464
2024-05-05  2560  365.714286  488
2024-05-12  2061  294.428571  462
2024-05-19  2209  315.571429  494
2024-05-26  2036  290.857143  495
2024-06-02  1941  277.285714  444
2024-06-09  2715  387.857143  480
2024-06-16  1606  229.428571  424
2024-06-23  2158  308.285714  493
2024-06-30  1984  283.428571  450
2024-07-07  2274  324.857143  419
2024-07-14  1737  248.142857  372
2024-07-21  1919  274.142857  477
2024-07-28  2241  320.142857  445
2024-08-04  2062  294.571429  497
2024-08-11  1942  277.428571  462
2024-08-18  2051  293.000000  345
2024-08-25  2270  324.285714  494
2024-09-01  2165  309.285714  418
2024-09-08  1737  248.142857  497
2024-09-15  2613  373.285714  495
2024-09-22  2012  287.428571  407
2024-09-29  1897  271.000000  436
2024-10-06  2418  345.428571  491
2024-10-13  1567  223.857143  397
2024-10-20  2465  352.142857  487
2024-10-27  2135  305.000000  439
2024-11-03  2415  345.000000  497
2024-11-10  2119  302.714286  429
2024-11-17  2031  290.142857  477
2024-11-24  2257  322.428571  493
2024-12-01  2432  347.428571  453
2024-12-08  2222  317.428571  465
2024-12-15  1992  284.571429  492
2024-12-22  1890  270.000000  386
2024-12-29  2092  298.857143  473
2025-01-05  2285  326.428571  449
2025-01-12  2582  368.857143  478
2025-01-19  2727  389.571429  485
2025-01-26  2350  335.714286  463
2025-02-02  1822  260.285714  472
2025-02-09  2431  347.285714  497
2025-02-16  2909  415.571429  491
2025-02-23  2272  324.571429  444
2025-03-02  2266  323.714286  421
2025-03-09  1829  261.285714  386
2025-03-16  2174  310.571429  497
2025-03-23  2195  313.571429  486
2025-03-30  1821  260.142857  368
2025-04-06  2287  326.714286  492
2025-04-13  2818  402.571429  488
2025-04-20  2008  286.857143  475
2025-04-27  1463  209.000000  376
2025-05-04  1912  273.142857  454
2025-05-11  2150  307.142857  459
2025-05-18  2323  331.857143  442
2025-05-25  2479  354.142857  441
2025-06-01  2378  339.714286  497
2025-06-08  2649  378.428571  477
2025-06-15  1491  213.000000  384
2025-06-22  2206  315.142857  440
2025-06-29  2229  318.428571  448
2025-07-06  2236  319.428571  422
2025-07-13  2672  381.714286  486
2025-07-20  2138  305.428571  439
2025-07-27  1965  280.714286  427
2025-08-03  2251  321.571429  487
2025-08-10  2547  363.857143  486
2025-08-17  1677  239.571429  475
2025-08-24  2348  335.428571  479
2025-08-31  2276  325.142857  482
2025-09-07  2566  366.571429  476
2025-09-14  2426  346.571429  482
2025-09-21  1686  240.857143  335
2025-09-28  1812  258.857143  344
2025-10-05  2095  299.285714  449
2025-10-12  1679  239.857143  423
2025-10-19  1841  263.000000  439
2025-10-26  2295  327.857143  484
2025-11-02  1861  265.857143  398
2025-11-09  2094  299.142857  450
2025-11-16  2501  357.285714  463
2025-11-23  1912  273.142857  490
2025-11-30  2038  291.142857  471
2025-12-07  2418  345.428571  498
2025-12-14  1824  260.571429  399
2025-12-21  2255  322.142857  448
2025-12-28  1987  283.857143  427
2026-01-04  2133  304.714286  445
2026-01-11  2195  313.571429  469
2026-01-18  1771  253.000000  416
2026-01-25  2159  308.428571  433
2026-02-01  2239  319.857143  489
2026-02-08  2282  326.000000  468
2026-02-15  2008  286.857143  465
2026-02-22  2411  344.428571  472
2026-03-01  1884  269.142857  497
2026-03-08  2094  299.142857  487
2026-03-15   673  336.500000  444

In [212]:
## monthly sales
df.resample("M").sum()

C:\Users\prash\AppData\Local\Temp\ipykernel_23316\963759446.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample("M").sum()

            Sales
Date
2024-01-31   9765
2024-02-29   9019
2024-03-31   8250
2024-04-30   9165
2024-05-31   9646
2024-06-30   9039
2024-07-31   8964
2024-08-31   9463
2024-09-30   8984
2024-10-31   9495
2024-11-30   9400
2024-12-31   9320
2025-01-31  10418
2025-02-28  10021
2025-03-31   9019
2025-04-30   8806
2025-05-31  10157
2025-06-30   9336
2025-07-31   9785
2025-08-31   9953
2025-09-30   9106
2025-10-31   8497
2025-11-30   9203
2025-12-31   9348
2026-01-31   9392
2026-02-28   8503
2026-03-31   3090

In [213]:
df.resample("Y").sum()

C:\Users\prash\AppData\Local\Temp\ipykernel_23316\3008989606.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  df.resample("Y").sum()

             Sales
Date
2024-12-31  110510
2025-12-31  113649
2026-12-31   20985

In [214]:
patient_data

,Patient_ID,Patient_Name,Patient_Age,Email,Policy_Number,Policy_Type,year,Provider_Name,Coverage_Amount,Start_Year,Patient_Age_category,Mask_Age_example,Age_remark,Email_domain,risk_factor,policy_map,First_name,Last_name,rolling_avg
17,340,Ishaan Kumar,77,ishaan.kumar451@outlook.com,POL875129,Basic,2025,India Insurance,233949,2023,Older Age,Older Age,Senior,outlook.com,High Risk,B,Ishaan,Kumar,233949.000000
30,384,Aarav Singh,77,aarav.singh557@yahoo.com,POL052224,Basic,2025,Max Bupa,661113,2023,Older Age,Older Age,Senior,yahoo.com,High Risk,B,Aarav,Singh,447531.000000
40,880,Reyansh Mehta,77,reyansh.mehta554@outlook.com,POL468441,Basic,2025,ICICI Lombard,223344,2023,Older Age,Older Age,Senior,outlook.com,High Risk,B,Reyansh,Mehta,372802.000000
52,912,Sai Kumar,77,sai.kumar119@outlook.com,POL544288,Basic,2025,ICICI Lombard,513156,2023,Older Age,Older Age,Senior,outlook.com,High Risk,B,Sai,Kumar,465871.000000
87,213,Arjun Reddy,77,arjun.reddy424@gmail.com,POL101484,Basic,2025,Max Bupa,665410,2023,Older Age,Older Age,Senior,gmail.com,High Risk,B,Arjun,Reddy,467303.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1954,1953,Aditya Joshi,31,aditya.joshi357@outlook.com,POL859688,Premium,2026,India Insurance,821254,2026,Middle Age,Middle Age,Middle Age,outlook.com,Age is below 50,Pre,Aditya,Joshi,692585.666667
1967,1966,Vihaan Mehta,77,vihaan.mehta781@outlook.com,POL545586,Premium,2026,ICICI Lombard,661434,2026,Older Age,Older Age,Senior,outlook.com,Age is below 50,Pre,Vihaan,Mehta,817166.666667
1968,1967,Reyansh Joshi,33,reyansh.joshi279@yahoo.com,POL690400,Premium,2026,HDFC Ergo,460896,2026,Middle Age,Middle Age,Middle Age,yahoo.com,Age is below 50,Pre,Reyansh,Joshi,647861.333333
1982,1981,Sai Verma,77,sai.verma933@gmail.com,POL355570,Premium,2026,Star Health,325225,2026,Older Age,Older Age,Senior,gmail.com,Age is below 50,Pre,Sai,Verma,482518.333333
1991,1990,Krishna Yadav,49,krishna.yadav340@yahoo.com,POL193513,Premium,2026,Star Health,327837,2026,Middle Age,Middle Age,Middle Age,yahoo.com,Age is below 50,Pre,Krishna,Yadav,371319.333333

In [215]:
data = {
    "timestamp":[
        "2025-01-01T10:30:45",
        "2025-02-23T10:30:45",
        "2025-03-31T09:20:10",
        "2025-06-30T12:45:30",
        "2025-12-31T23:10:05"
    ]
}

In [216]:
data

{'timestamp': ['2025-01-01T10:30:45',
  '2025-02-23T10:30:45',
  '2025-03-31T09:20:10',
  '2025-06-30T12:45:30',
  '2025-12-31T23:10:05']}

In [217]:
df = pd.DataFrame(data)

In [218]:
df

             timestamp
0  2025-01-01T10:30:45
1  2025-02-23T10:30:45
2  2025-03-31T09:20:10
3  2025-06-30T12:45:30
4  2025-12-31T23:10:05

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  5 non-null      object
dtypes: object(1)
memory usage: 172.0+ bytes

In [220]:
df["datetime"]=pd.to_datetime(df["timestamp"])

In [221]:
df

             timestamp            datetime
0  2025-01-01T10:30:45 2025-01-01 10:30:45
1  2025-02-23T10:30:45 2025-02-23 10:30:45
2  2025-03-31T09:20:10 2025-03-31 09:20:10
3  2025-06-30T12:45:30 2025-06-30 12:45:30
4  2025-12-31T23:10:05 2025-12-31 23:10:05

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  5 non-null      object
 1   datetime   5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 212.0+ bytes

In [223]:
## year from the datetime

df['year']=df['datetime'].dt.year

In [224]:
df

             timestamp            datetime  year
0  2025-01-01T10:30:45 2025-01-01 10:30:45  2025
1  2025-02-23T10:30:45 2025-02-23 10:30:45  2025
2  2025-03-31T09:20:10 2025-03-31 09:20:10  2025
3  2025-06-30T12:45:30 2025-06-30 12:45:30  2025
4  2025-12-31T23:10:05 2025-12-31 23:10:05  2025

In [227]:
## month from date time

df['Month']= df['datetime'].dt.month

In [228]:
df

             timestamp            datetime  year  Month
0  2025-01-01T10:30:45 2025-01-01 10:30:45  2025      1
1  2025-02-23T10:30:45 2025-02-23 10:30:45  2025      2
2  2025-03-31T09:20:10 2025-03-31 09:20:10  2025      3
3  2025-06-30T12:45:30 2025-06-30 12:45:30  2025      6
4  2025-12-31T23:10:05 2025-12-31 23:10:05  2025     12

In [231]:
## extract month name from the date time columns

df["Month_Name"]=df['datetime'].dt.month_name()

In [232]:
df

             timestamp            datetime  year  Month Month_Name
0  2025-01-01T10:30:45 2025-01-01 10:30:45  2025      1    January
1  2025-02-23T10:30:45 2025-02-23 10:30:45  2025      2   February
2  2025-03-31T09:20:10 2025-03-31 09:20:10  2025      3      March
3  2025-06-30T12:45:30 2025-06-30 12:45:30  2025      6       June
4  2025-12-31T23:10:05 2025-12-31 23:10:05  2025     12   December

In [233]:
## extract day_name from the datetime

df['Day_Name']=df['datetime'].dt.day_name()

In [234]:
df

             timestamp            datetime  year  Month Month_Name   Day_Name
0  2025-01-01T10:30:45 2025-01-01 10:30:45  2025      1    January  Wednesday
1  2025-02-23T10:30:45 2025-02-23 10:30:45  2025      2   February     Sunday
2  2025-03-31T09:20:10 2025-03-31 09:20:10  2025      3      March     Monday
3  2025-06-30T12:45:30 2025-06-30 12:45:30  2025      6       June     Monday
4  2025-12-31T23:10:05 2025-12-31 23:10:05  2025     12   December  Wednesday

In [235]:
##check day is weekday or weekend

df['is_Weekend']=df['datetime'].dt.dayofweek>4

In [236]:
df

,timestamp,datetime,year,Month,Month_Name,Day_Name,is_Weekend
0,2025-01-01T10:30:45,2025-01-01 10:30:45,2025,1,January,Wednesday,False
1,2025-02-23T10:30:45,2025-02-23 10:30:45,2025,2,February,Sunday,True
2,2025-03-31T09:20:10,2025-03-31 09:20:10,2025,3,March,Monday,False
3,2025-06-30T12:45:30,2025-06-30 12:45:30,2025,6,June,Monday,False
4,2025-12-31T23:10:05,2025-12-31 23:10:05,2025,12,December,Wednesday,False

In [241]:
def is_weekend(df):
    if df['Day_Name']=='Sunday' or df['Day_Name']== 'Saturday':
        return "Weekend"
    else:
        return 'Weekday'

In [240]:
df.columns

Index(['timestamp', 'datetime', 'year', 'Month', 'Month_Name', 'Day_Name',
       'is_Weekend'],
      dtype='object')

In [242]:
df['is_Weekend_2']=df.apply(is_weekend,axis=1)

In [243]:
df

,timestamp,datetime,year,Month,Month_Name,Day_Name,is_Weekend,is_Weekend_2
0,2025-01-01T10:30:45,2025-01-01 10:30:45,2025,1,January,Wednesday,False,Weekday
1,2025-02-23T10:30:45,2025-02-23 10:30:45,2025,2,February,Sunday,True,Weekend
2,2025-03-31T09:20:10,2025-03-31 09:20:10,2025,3,March,Monday,False,Weekday
3,2025-06-30T12:45:30,2025-06-30 12:45:30,2025,6,June,Monday,False,Weekday
4,2025-12-31T23:10:05,2025-12-31 23:10:05,2025,12,December,Wednesday,False,Weekday

In [244]:
df['quarter']=df['datetime'].dt.quarter

In [245]:
df

,timestamp,datetime,year,Month,Month_Name,Day_Name,is_Weekend,is_Weekend_2,quarter
0,2025-01-01T10:30:45,2025-01-01 10:30:45,2025,1,January,Wednesday,False,Weekday,1
1,2025-02-23T10:30:45,2025-02-23 10:30:45,2025,2,February,Sunday,True,Weekend,1
2,2025-03-31T09:20:10,2025-03-31 09:20:10,2025,3,March,Monday,False,Weekday,1
3,2025-06-30T12:45:30,2025-06-30 12:45:30,2025,6,June,Monday,False,Weekday,2
4,2025-12-31T23:10:05,2025-12-31 23:10:05,2025,12,December,Wednesday,False,Weekday,4

In [246]:
df['is_leap_year'] = df['datetime'].dt.is_leap_year

In [247]:
df

,timestamp,datetime,year,Month,Month_Name,Day_Name,is_Weekend,is_Weekend_2,quarter,is_leap_year
0,2025-01-01T10:30:45,2025-01-01 10:30:45,2025,1,January,Wednesday,False,Weekday,1,False
1,2025-02-23T10:30:45,2025-02-23 10:30:45,2025,2,February,Sunday,True,Weekend,1,False
2,2025-03-31T09:20:10,2025-03-31 09:20:10,2025,3,March,Monday,False,Weekday,1,False
3,2025-06-30T12:45:30,2025-06-30 12:45:30,2025,6,June,Monday,False,Weekday,2,False
4,2025-12-31T23:10:05,2025-12-31 23:10:05,2025,12,December,Wednesday,False,Weekday,4,False

In [250]:
## weeknumber of the year

df['week_number']=df['datetime'].dt.isocalendar().week

In [251]:
df

,timestamp,datetime,year,Month,Month_Name,Day_Name,is_Weekend,is_Weekend_2,quarter,is_leap_year,week_number
0,2025-01-01T10:30:45,2025-01-01 10:30:45,2025,1,January,Wednesday,False,Weekday,1,False,1
1,2025-02-23T10:30:45,2025-02-23 10:30:45,2025,2,February,Sunday,True,Weekend,1,False,8
2,2025-03-31T09:20:10,2025-03-31 09:20:10,2025,3,March,Monday,False,Weekday,1,False,14
3,2025-06-30T12:45:30,2025-06-30 12:45:30,2025,6,June,Monday,False,Weekday,2,False,27
4,2025-12-31T23:10:05,2025-12-31 23:10:05,2025,12,December,Wednesday,False,Weekday,4,False,1

In [252]:
## day of the year

df['day_of_year']= df['datetime'].dt.dayofyear

In [253]:
df

,timestamp,datetime,year,Month,Month_Name,Day_Name,is_Weekend,is_Weekend_2,quarter,is_leap_year,week_number,day_of_year
0,2025-01-01T10:30:45,2025-01-01 10:30:45,2025,1,January,Wednesday,False,Weekday,1,False,1,1
1,2025-02-23T10:30:45,2025-02-23 10:30:45,2025,2,February,Sunday,True,Weekend,1,False,8,54
2,2025-03-31T09:20:10,2025-03-31 09:20:10,2025,3,March,Monday,False,Weekday,1,False,14,90
3,2025-06-30T12:45:30,2025-06-30 12:45:30,2025,6,June,Monday,False,Weekday,2,False,27,181
4,2025-12-31T23:10:05,2025-12-31 23:10:05,2025,12,December,Wednesday,False,Weekday,4,False,1,365

In [254]:
## how to extract hours , minutes and second
df['hours']=df['datetime'].dt.hour

In [255]:
df['minutes']=df['datetime'].dt.minute

In [256]:
df['second']=df['datetime'].dt.second

In [257]:
df

,timestamp,datetime,year,Month,Month_Name,Day_Name,is_Weekend,is_Weekend_2,quarter,is_leap_year,week_number,day_of_year,hours,minutes,second
0,2025-01-01T10:30:45,2025-01-01 10:30:45,2025,1,January,Wednesday,False,Weekday,1,False,1,1,10,30,45
1,2025-02-23T10:30:45,2025-02-23 10:30:45,2025,2,February,Sunday,True,Weekend,1,False,8,54,10,30,45
2,2025-03-31T09:20:10,2025-03-31 09:20:10,2025,3,March,Monday,False,Weekday,1,False,14,90,9,20,10
3,2025-06-30T12:45:30,2025-06-30 12:45:30,2025,6,June,Monday,False,Weekday,2,False,27,181,12,45,30
4,2025-12-31T23:10:05,2025-12-31 23:10:05,2025,12,December,Wednesday,False,Weekday,4,False,1,365,23,10,5

In [258]:
## how to save the data into csv and excel 

file_name='date.csv'


df.to_csv(file_name,index=False)

In [259]:
import os 

dir_path = os.path.expanduser('~\downloads')

print(dir_path)

folder_name= 'datayt_check_list_import'

folder_path = os.path.join(dir_path,folder_name)

print(folder_path)

os.makedirs(folder_path,exist_ok=True)

file_name= 'data.csv'

file_path = os.path.join(folder_path,file_name)

print(file_path)

df.to_csv(file_path,index=False)

C:\Users\prash\downloads
C:\Users\prash\downloads\datayt_check_list_import
C:\Users\prash\downloads\datayt_check_list_import\data.csv

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\prash\AppData\Local\Temp\ipykernel_23316\410969058.py:3: SyntaxWarning: invalid escape sequence '\d'
  dir_path = os.path.expanduser('~\downloads')

In [260]:
df1 = pd.DataFrame({
    "Name": ["Amit", "Ravi", "Priya"],
    "Age": [25, 30, 28]
})

df2 = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet"],
    "Price": [80000, 30000, 25000]
})

In [261]:
df1

    Name  Age
0   Amit   25
1   Ravi   30
2  Priya   28

In [262]:
df2

  Product  Price
0  Laptop  80000
1   Phone  30000
2  Tablet  25000

In [267]:
dir_path = os.path.expanduser('~\downloads')

print(dir_path)

folder_name= 'excel_data_from_pandas'

folder_path = os.path.join(dir_path,folder_name)

print(folder_path)

os.makedirs(folder_path,exist_ok=True)

excel_path='product.xlsx'

file_path = os.path.join(folder_path,excel_path)

print(file_path)

C:\Users\prash\downloads
C:\Users\prash\downloads\excel_data_from_pandas
C:\Users\prash\downloads\excel_data_from_pandas\product.xlsx

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\prash\AppData\Local\Temp\ipykernel_23316\2166179243.py:1: SyntaxWarning: invalid escape sequence '\d'
  dir_path = os.path.expanduser('~\downloads')

In [268]:



writer = pd.ExcelWriter(file_path)

df1.to_excel(writer,sheet_name='person.destails',index=False)
df2.to_excel(writer,sheet_name='product_details',index=False)

writer.close()